import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, CheckCircle2, ClipboardCheck, Clock3, List, RefreshCw, RotateCcw, Search, XCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { assetApi } from '../../api/modules/assetApi';
import { managerApi } from '../../api/modules/managerApi';
import { useAuth } from '../../auth/useAuth';
import { Badge } from '../../components/common/Badge';
import { LoadingState } from '../../components/common/LoadingState';
import { Toast } from '../../components/common/Toast';
import type { ApiError } from '../../types';
import type { Asset } from '../../types/assets';
import type { ManagerPendingRequisition, ManagerRequisitionDetail } from '../../types/manager';

type Row={queue:ManagerPendingRequisition;detail:ManagerRequisitionDetail|null};
const pageSize=5;
const message=(error:unknown)=>{const value=error as ApiError;return[value.message,...(value.errors??[]),value.traceId&&`Trace: ${value.traceId}`].filter(Boolean).join(' ')};
export function ManagerDashboardPage(){
 const{user}=useAuth();const[rows,setRows]=useState<Row[]>([]);const[assets,setAssets]=useState<Asset[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[query,setQuery]=useState('');const[status,setStatus]=useState('ALL');const[category,setCategory]=useState('ALL');const[from,setFrom]=useState('');const[to,setTo]=useState('');const[page,setPage]=useState(1);const[updated,setUpdated]=useState(new Date());
 const load=()=>{setLoading(true);Promise.all([managerApi.pending(),assetApi.search({isActive:true})]).then(async([queue,assetList])=>{const details=await Promise.all(queue.map(x=>managerApi.detail(x.id).catch(()=>null)));setRows(queue.map((x,i)=>({queue:x,detail:details[i]??null})));setAssets(assetList);setUpdated(new Date())}).catch(e=>setError(message(e))).finally(()=>setLoading(false))};
 useEffect(load,[]);
 const assetById=useMemo(()=>new Map(assets.map(x=>[x.id,x])),[assets]);const categories=useMemo(()=>Array.from(new Set(assets.map(x=>x.categoryName).filter((x):x is string=>Boolean(x)))).sort(),[assets]);
 const visible=useMemo(()=>rows.filter(({queue,detail})=>{const itemAssets=detail?.items.map(x=>assetById.get(x.assetId));const text=`${queue.number} ${queue.requestedByName} ${queue.requestedByEmployeeId} ${detail?.items.map(x=>x.assetName).join(' ')}`.toLowerCase();const date=queue.requestedDate.slice(0,10);return text.includes(query.toLowerCase())&&(status==='ALL'||queue.status===status)&&(category==='ALL'||itemAssets?.some(x=>x?.categoryName===category))&&(!from||date>=from)&&(!to||date<=to)}),[rows,query,status,category,from,to,assetById]);
 const pages=Math.max(1,Math.ceil(visible.length/pageSize));const shown=visible.slice((Math.min(page,pages)-1)*pageSize,Math.min(page,pages)*pageSize);const reset=()=>{setQuery('');setStatus('ALL');setCategory('ALL');setFrom('');setTo('');setPage(1)};
 if(loading)return <LoadingState label="Loading Manager dashboard…"/>;
 return <div className="manager-page"><header className="manager-welcome"><div><h1>Welcome, {user?.fullName}</h1><p>{user?.designation}, {user?.orgUnitName}</p></div><button className="manager-updated" onClick={load}><RefreshCw/> Last updated: {updated.toLocaleString('en-GB')}</button></header><h2 className="manager-overview-title">Overview</h2>
 <section className="manager-metrics"><Metric icon={<ClipboardCheck/>} value={rows.length} label="Pending Verification" description="Requisitions awaiting your decision." tone="amber"/><Metric icon={<CheckCircle2/>} value="—" label="Approved & Forwarded" description="Approved requisitions sent onward." tone="green"/><Metric icon={<RotateCcw/>} value="—" label="Returned to Maker" description="Returned for correction or more information." tone="blue"/><Metric icon={<XCircle/>} value="—" label="Rejected" description="Rejected requisitions." tone="red"/></section>
 <section className="manager-recent-heading"><h2>Recently Submitted Requisitions</h2><Link className="button button--secondary" to="/manager/requisitions"><List/> View All Requisitions</Link></section>
 <section className="manager-list"><div className="manager-filters"><label className="manager-search"><Search/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Search by Requisition ID, Item or Maker"/></label><label className="manager-filter-field"><span>Status</span><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="ALL">All</option><option value="SUBMITTED">Pending Verification</option></select></label><label className="manager-filter-field"><span>Asset Category</span><select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="ALL">All</option>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label className="manager-filter-field date"><span>Submission Date</span><div><input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}}/><ArrowRight/><input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1)}}/></div></label><button className="manager-reset" onClick={reset}><RefreshCw/> Reset</button></div>
 <div className="manager-table"><div className="manager-row manager-row-head"><span>Requisition ID</span><span>Asset / Item</span><span>Category</span><span>Maker</span><span>Quantity</span><span>Submitted On</span><span>Status</span><span>Action</span></div>{shown.map(({queue,detail})=>{const first=detail?.items[0];return <div className="manager-row" key={queue.id}><strong>{queue.number}</strong><span>{detail?.items.map(x=>x.assetName).join(', ')||'—'}</span><span>{first?assetById.get(first.assetId)?.categoryName||'—':'—'}</span><span><b>{queue.requestedByName}</b><small>{queue.requestedByEmployeeId}</small></span><span>{detail?.items.reduce((sum,x)=>sum+x.quantity,0)??queue.itemCount}</span><span>{new Date(queue.requestedDate).toLocaleDateString('en-GB')}<small>{new Date(queue.requestedDate).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</small></span><Badge tone="warning">Pending Verification</Badge><Link className="manager-action" to={`/manager/requisitions/${queue.id}`}>Approve</Link></div>})}{shown.length===0&&<p className="manager-empty">No pending requisitions match the selected filters.</p>}</div>
 <footer className="manager-table-footer"><span>Showing {visible.length?((page-1)*pageSize)+1:0} to {Math.min(page*pageSize,visible.length)} of {visible.length} entries</span><div><button disabled={page===1} onClick={()=>setPage(x=>x-1)}>‹</button>{Array.from({length:pages},(_,i)=>i+1).map(x=><button className={page===x?'active':''} onClick={()=>setPage(x)} key={x}>{x}</button>)}<button disabled={page===pages} onClick={()=>setPage(x=>x+1)}>›</button></div></footer></section><div className="manager-note"><Clock3/> Please review requisitions on time to ensure smooth processing.</div>{error&&<Toast tone="error" message={error} onClose={()=>setError('')}/>}</div>;
}
function Metric({icon,value,label,description,tone}:{icon:React.ReactNode;value:number|string;label:string;description:string;tone:string}){return <article className={`manager-metric ${tone}`}>{icon}<div><strong>{value}</strong><b>{label}</b><small>{description}</small><a href="#manager-table">View all <ArrowRight/></a></div></article>}
