import { useEffect, useState } from 'react';
import { AlertTriangle, ArrowLeft, Building2, CalendarDays, CheckCircle2, Eye, Package, RefreshCw, RotateCcw, Send, UserRound, XCircle } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { assetApi } from '../../api/modules/assetApi';
import { managerApi } from '../../api/modules/managerApi';
import { useAuth } from '../../auth/useAuth';
import { Badge } from '../../components/common/Badge';
import { Button } from '../../components/common/Button';
import { ConfirmModal } from '../../components/common/ConfirmModal';
import { LoadingState } from '../../components/common/LoadingState';
import { Toast } from '../../components/common/Toast';
import { AttachmentPreview } from '../../components/maker/AttachmentPreview';
import type { ApiError } from '../../types';
import type { ManagerActionResult, ManagerRequisitionDetail } from '../../types/manager';
type Action='approve'|'return'|'reject';
const describe=(error:unknown)=>{const e=error as ApiError;const prefix=e.status===409?'This requisition was already processed or its workflow state changed.':e.status===403?'You are not authorized to act on this requisition.':e.status===401?'Your session is no longer authorized.':e.message;return[prefix,...(e.errors??[]),e.traceId&&`Trace: ${e.traceId}`].filter(Boolean).join(' ')};
export function ManagerRequisitionPage(){
 const{id}=useParams();const{user}=useAuth();const[data,setData]=useState<ManagerRequisitionDetail|null>(null);const[makerName,setMakerName]=useState('');const[category,setCategory]=useState('—');const[action,setAction]=useState<Action>('approve');const[remarks,setRemarks]=useState('');const[confirm,setConfirm]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[actionError,setActionError]=useState('');const[result,setResult]=useState<ManagerActionResult|null>(null);
 useEffect(()=>{const requisitionId=Number(id);Promise.all([managerApi.detail(requisitionId),managerApi.pending(),assetApi.categories()]).then(async([detail,pending,categories])=>{setData(detail);setMakerName(pending.find(x=>x.id===requisitionId)?.requestedByName||detail.requestedByEmployeeId);const first=detail.items[0];if(first){const asset=await assetApi.get(first.assetId).catch(()=>null);setCategory(asset?.categoryName||categories.find(x=>x.id===asset?.assetCategoryId)?.name||'—')}}).catch(e=>setError(describe(e)))},[id]);
 const execute=async()=>{if((action==='return'||action==='reject')&&!remarks.trim()){setError(`Remarks are mandatory when you ${action==='return'?'return to Maker':'reject'} a requisition.`);setConfirm(false);return}setBusy(true);setConfirm(false);setActionError('');try{const value=action==='approve'?await managerApi.approve(Number(id),remarks.trim()||null):action==='return'?await managerApi.returnToMaker(Number(id),remarks.trim()):await managerApi.reject(Number(id),remarks.trim());setResult(value)}catch(e){setActionError(describe(e))}finally{setBusy(false)}};
 if(!data&&!error)return <LoadingState label="Loading Manager review…"/>;if(!data)return <div className="manager-page"><Link to="/manager/requisitions"><ArrowLeft/> Back to Dashboard</Link>{error&&<Toast tone="error" message={error} onClose={()=>setError('')}/>}</div>;
 if(result)return <ManagerResult data={data} action={action} result={result} remarks={remarks} makerName={makerName} actor={user?.fullName||'Manager'}/>;
 if(actionError)return <ManagerFailure data={data} error={actionError} makerName={makerName} retry={()=>void execute()}/>;
 const first=data.items[0];return <div className="manager-page manager-review manager-approval-screen">
  <header className="approval-summary"><div><small>Requisition ID</small><div className="approval-id"><h1>{data.number}</h1><Badge tone="warning">Pending Verification</Badge></div></div><div className="approval-maker"><span className="approval-avatar"><UserRound/></span><span><small>Maker</small><strong>{makerName}</strong><b>{data.requestedByEmployeeId} <i>•</i> {data.orgUnitName}</b></span></div><div><small>Submission Time</small><strong>{new Date(data.requestedDate).toLocaleString('en-GB')}</strong></div></header>
  <div className="approval-layout"><main>
   <section className="manager-card approval-primary"><h2>Primary Specifications Card</h2><div className="approval-primary-grid"><Detail label="Asset Category" value={category}/><Detail label="Item / Asset" value={first?.assetName||'—'}/><Detail label="Requisition Type" value={first?.requisitionType.replaceAll('_',' ')||'—'} badge/><Detail label="Quantity" value={first?String(first.quantity):'—'}/></div>{first&&<div className="approval-purpose"><Detail label="Purpose / Business Justification" value={first.purposeJustification}/><Detail label="Additional Specification / Requirement" value={first.additionalSpecificationRequirement||'—'}/></div>}{data.items.length>1&&<p className="approval-more-items">This requisition contains {data.items.length} items. All submitted item details are shown below.</p>}</section>
   {first&&first.dynamicSpecifications.length>0&&<section className="manager-card approval-specifications"><h2>General Specifications</h2><div className="approval-primary-grid">{first.dynamicSpecifications.map(spec=><Detail key={spec.specId} label={spec.name} value={formatSpec(spec)}/>)}</div></section>}
   <section className="manager-card"><h2>Attachments &amp; Verification Card</h2>{data.attachments.length?data.attachments.map(x=><AttachmentPreview key={x.id} attachment={x} requisitionId={data.id}/>):<p className="approval-no-file">No attachment was submitted.</p>}</section>
   {first?.replacementInfo&&<section className="manager-card approval-replacement"><h2>Old Asset Handover (Replacement Only) Card</h2><div className="approval-handover"><Detail label="Asset Tag" value={first.replacementInfo.assetTag||'—'}/><Detail label="Serial No." value={first.replacementInfo.serial||'—'}/><Detail label="Reason for Replacement" value={first.replacementInfo.currentCondition}/></div></section>}
  </main><aside><section className="manager-card approval-actions"><h2>Select Action</h2><ActionChoice active={action==='approve'} tone="approve" icon={<CheckCircle2/>} title="Approve & Forward" text="Forward using the API/database workflow route." onClick={()=>setAction('approve')}/><ActionChoice active={action==='return'} tone="return" icon={<RotateCcw/>} title="Return to Maker" text="Return for correction or more information." onClick={()=>setAction('return')}/><ActionChoice active={action==='reject'} tone="reject" icon={<XCircle/>} title="Reject" text="Reject this requisition." onClick={()=>setAction('reject')}/></section><section className="manager-card approval-remarks"><h2>Checker Remarks {(action==='return'||action==='reject')&&<b>*</b>}</h2><p>{action==='approve'?'Add approval remarks if applicable.':'Enter reason for rejection/revision (Required)'}</p><textarea maxLength={500} value={remarks} onChange={e=>setRemarks(e.target.value)} placeholder={action==='approve'?'Enter remarks (Optional)':`Enter reason for ${action} (Required)`}/><small>{remarks.length} / 500 characters</small></section></aside></div>
  <footer className="manager-review-actions approval-footer"><Link className="button button--secondary" to="/manager/requisitions"><ArrowLeft/> Back to Dashboard</Link><Button disabled={busy} onClick={()=>setConfirm(true)}><Send/> {busy?'Processing…':'Confirm & Execute Action'}</Button></footer><ConfirmModal open={confirm} title={`Confirm ${action==='approve'?'Approval':action==='return'?'Return to Maker':'Rejection'}`} message="This action is validated transactionally against the current workflow state and cannot be duplicated." onCancel={()=>setConfirm(false)} onConfirm={()=>void execute()}/>{error&&<Toast tone="error" message={error} onClose={()=>setError('')}/>}</div>;
}
type Spec=ManagerRequisitionDetail['items'][number]['dynamicSpecifications'][number];
const formatSpec=(spec:Spec)=>{if(spec.options.length)return spec.options.map(x=>x.value).join(', ');switch(spec.type){case'NUMBER':return spec.numberValue?.toString()??'—';case'YES_NO':return spec.boolValue===null?'—':spec.boolValue?'Yes':'No';case'DATE':return spec.dateValue??'—';default:return spec.textValue??'—'}};
function Detail({label,value,badge}:{label:string;value:string;badge?:boolean}){return <div className="approval-detail"><small>{label}</small>{badge?<Badge tone="warning">{value}</Badge>:<strong>{value}</strong>}</div>}
function ActionChoice({active,tone,icon,title,text,onClick}:{active:boolean;tone:string;icon:React.ReactNode;title:string;text:string;onClick:()=>void}){return <button className={`manager-choice ${tone} ${active?'active':''}`} onClick={onClick}>{icon}<span><strong>{title}</strong><small>{text}</small></span></button>}
// @ts-expect-error -- detail rendering is delegated to OutcomeSummary.
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function ManagerResult({data,action,result,remarks,makerName,actor}:{data:ManagerRequisitionDetail;action:Action;result:ManagerActionResult;remarks:string;makerName:string;actor:string}){const approved=action==='approve';const rejected=action==='reject';const item=data.items[0];const actionLabel=approved?'Approved & Forwarded':rejected?'Rejected':'Returned to Maker';return <div className="manager-outcome"><header><h1><ArrowLeft/> {approved?'Approval Successful':rejected?'Rejection Successful':'Return Successful'}</h1><p>{result.resultMessage}</p></header><section className={`outcome-hero ${rejected?'failure':'success'}`}><div className="outcome-symbol">{rejected?<XCircle/>:<CheckCircle2/>}</div><div><h2>{approved?'Approved Successfully!':rejected?'Requisition Rejected Successfully!':'Returned to Maker Successfully!'}</h2><p>{approved?'The requisition has been approved and forwarded using the database workflow.':result.resultMessage}</p><div className="outcome-pills"><span>Requisition ID: <strong>{data.number}</strong></span><span>Current Status: <strong>{result.referenceNo?.replaceAll('_',' ')||actionLabel}</strong></span></div></div></section><OutcomeSummary data={data} makerName={makerName}/>{remarks&&<section className="outcome-remarks"><h2>Manager Remarks</h2><p>{remarks}</p></section>}<section className="outcome-action-info"><div><UserRound/><span><small>Action Taken By</small><strong>{actor}</strong><b>Branch Manager</b></span></div><div><CheckCircle2/><span><small>Action</small><strong>{actionLabel}</strong></span></div><div><CalendarDays/><span><small>Action Date &amp; Time</small><strong>{new Date().toLocaleString('en-GB')}</strong></span></div></section><div className="outcome-note">The request has moved to <strong>{result.referenceNo?.replaceAll('_',' ')||'the next database-controlled stage'}</strong>.</div><footer><Link className="button button--secondary" to="/manager/requisitions"><ArrowLeft/> Back to Dashboard</Link><Link className="button" to={`/manager/requisitions/${data.id}`}><Eye/> View Requisition Details</Link></footer></div>}
function ManagerFailure({data,error,makerName,retry}:{data:ManagerRequisitionDetail;error:string;makerName:string;retry:()=>void}){return <div className="manager-outcome failure-page"><header><h1><ArrowLeft/> Submission Failed</h1><p>We couldn't process your action. Please review the details below and try again.</p></header><section className="outcome-hero failure"><div className="outcome-symbol"><XCircle/></div><div><h2>Submission Failed!</h2><p>Your action could not be completed. No successful action has been recorded.</p><div className="outcome-pills"><span>Requisition ID: <strong>{data.number}</strong></span><span>Status: <strong>Action Not Completed</strong></span></div></div></section><section className="outcome-warning"><AlertTriangle/><div><h2>What Happened?</h2><p>There was a problem while submitting your action. Review the server response below and try again.</p></div></section><OutcomeSummary data={data} makerName={makerName}/><section className="outcome-error"><h2>Error Details</h2><p>{error}</p></section><div className="outcome-note">Your action has not been recorded. You can retry or return to the dashboard.</div><footer><Link className="button button--secondary" to="/manager/requisitions"><ArrowLeft/> Back to Dashboard</Link><Button onClick={retry}><RefreshCw/> Try Again</Button></footer></div>}
function OutcomeSummary({data,makerName}:{data:ManagerRequisitionDetail;makerName:string}){const item=data.items[0];return <section className="outcome-summary"><h2>Requisition Summary</h2><div><OutcomeCell icon={<UserRound/>} label="Maker" value={makerName} sub={data.requestedByEmployeeId}/><OutcomeCell icon={<Building2/>} label="Branch / Division" value={data.orgUnitName}/><OutcomeCell icon={<Package/>} label="Asset / Item" value={item?.assetName||'—'}/><OutcomeCell icon={<Package/>} label="Quantity" value={item?String(item.quantity):'—'}/><OutcomeCell icon={<RotateCcw/>} label="Requisition Type" value={item?.requisitionType.replaceAll('_',' ')||'—'}/></div><div className="outcome-dates"><OutcomeCell icon={<CalendarDays/>} label="Submission Date & Time" value={new Date(data.requestedDate).toLocaleString('en-GB')}/><OutcomeCell icon={<CalendarDays/>} label="Attempted / Completed On" value={new Date().toLocaleString('en-GB')}/></div></section>}
function OutcomeCell({icon,label,value,sub}:{icon:React.ReactNode;label:string;value:string;sub?:string}){return <div className="outcome-cell">{icon}<span><small>{label}</small><strong>{value}</strong>{sub&&<b>{sub}</b>}</span></div>}
