import{useEffect,useMemo,useState}from'react';
import{BriefcaseBusiness,Eye,FileSearch,Info,RotateCcw,Search,X}from'lucide-react';
import{assetApi}from'../../api/modules/assetApi';
import{procurementTrackingApi}from'../../api/modules/procurementTrackingApi';
import{LoadingState}from'../../components/common/LoadingState';
import{Toast}from'../../components/common/Toast';
import type{Asset}from'../../types/assets';
import type{BatchItemResult,ProcurementTrackingDetail,ProcurementTrackingRow}from'../../types/procurementTracking';
import'./ProcurementTrackingPage.css';
import'./ProcurementTrackingActions.css';

const today=()=>{
 const now=new Date(),offset=now.getTimezoneOffset()*60_000;
 return new Date(now.getTime()-offset).toISOString().slice(0,10);
};
const statusDateIso=(value:string)=>value===today()?new Date().toISOString():new Date(`${value}T00:00:00`).toISOString();
const tone=(s:string)=>s==='PROCUREMENT_COMPLETED'||s==='DELIVERED'?'green':s==='READY_FOR_PROCUREMENT'||s==='READY_FOR_WORK_ORDER'?'teal':s.includes('APPROVAL')?'purple':s.includes('PRICE')||s.includes('WORK_ORDER')?'orange':'blue';

export function ProcurementTrackingPage(){
 const[rows,setRows]=useState<ProcurementTrackingRow[]>([]),[assets,setAssets]=useState<Asset[]>([]),[statusOptions,setStatusOptions]=useState<[string,string][]>([]),[selected,setSelected]=useState<number[]>([]),[number,setNumber]=useState(''),[org,setOrg]=useState(''),[asset,setAsset]=useState(''),[status,setStatus]=useState(''),[detail,setDetail]=useState<ProcurementTrackingDetail|null>(null),[mode,setMode]=useState<'status'|'work-order'|null>(null),[results,setResults]=useState<BatchItemResult[]|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[newStatus,setNewStatus]=useState(''),[statusDate,setStatusDate]=useState(today()),[referenceNo,setReferenceNo]=useState(''),[statusRemarks,setStatusRemarks]=useState('');
 const[workOrderNo,setWorkOrderNo]=useState(''),[workOrderDate,setWorkOrderDate]=useState(today()),[supplier,setSupplier]=useState(''),[contractNo,setContractNo]=useState(''),[workOrderValue,setWorkOrderValue]=useState(''),[deliveryDate,setDeliveryDate]=useState(''),[workRemarks,setWorkRemarks]=useState('');
 const load=async(filters={})=>{setLoading(true);try{setRows(await procurementTrackingApi.search(filters))}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 useEffect(()=>{void load();assetApi.search({isActive:true}).then(setAssets).catch(()=>setAssets([]));procurementTrackingApi.statuses().then(x=>setStatusOptions(x.map(s=>[s.code,s.name]))).catch(e=>setError((e as Error).message))},[]);
 const selectedRows=useMemo(()=>rows.filter(x=>selected.includes(x.requisitionId)),[rows,selected]),orgs=useMemo(()=>[...new Map(rows.map(x=>[x.requestedOrgUnitId,x.orgUnitName])).entries()],[rows]);
 const search=()=>void load({requisitionNo:number.trim()||undefined,orgUnitId:org?Number(org):undefined,assetId:asset?Number(asset):undefined,statusCode:status||undefined});
 const reset=()=>{setNumber('');setOrg('');setAsset('');setStatus('');void load()};
 const toggle=(id:number)=>setSelected(x=>x.includes(id)?x.filter(y=>y!==id):[...x,id]);
 const open=async(id:number)=>{try{setDetail(await procurementTrackingApi.detail(id))}catch(e){setError((e as Error).message)}};
 const closeAction=()=>{setMode(null);setResults(null)};
 const submitStatus=async()=>{if(!newStatus){setError('New status is required.');return}setSaving(true);try{const x=await procurementTrackingApi.updateStatus({requisitionIds:selected,newStatusCode:newStatus,statusDate:statusDateIso(statusDate),referenceNo:referenceNo||undefined,remarks:statusRemarks||undefined});setResults(x.results);setNotice(x.failedCount?`Status update completed with ${x.failedCount} failure(s).`:'Status updated successfully.');setSelected([]);await load()}catch(e){setError((e as Error).message)}finally{setSaving(false)}};
 const submitWorkOrder=async()=>{if(!workOrderNo.trim()||!supplier.trim()||!workOrderDate||!workOrderValue){setError('Work Order No, date, supplier/vendor and value are required.');return}setSaving(true);try{const x=await procurementTrackingApi.assignWorkOrder({requisitionIds:selected,workOrderNo:workOrderNo.trim(),workOrderDate,supplierVendor:supplier.trim(),contractAgreementNo:contractNo||undefined,workOrderValue:Number(workOrderValue),deliveryDate:deliveryDate||undefined,remarks:workRemarks||undefined});setResults(x.results);setNotice(x.failedCount?`Work Order completed with ${x.failedCount} failure(s).`:'Work Order assigned and status changed to Work Order Issued.');setSelected([]);await load()}catch(e){setError((e as Error).message)}finally{setSaving(false)}};
 return <div className="pt-page"><div className="pt-crumb">Home › Procurement Tracking</div><header><h1>Procurement Tracking</h1><p>Track the progress of procurement activities performed outside this system.</p></header><section className="pt-note"><Info/><span><b>Tracking only.</b> The procurement process is performed manually; this screen records and displays its current progress.</span></section>
 <section className="pt-filters"><label><span>Requisition Number</span><input value={number}onChange={e=>setNumber(e.target.value)}placeholder="Enter requisition number"/></label><label><span>Branch / Division</span><select value={org}onChange={e=>setOrg(e.target.value)}><option value="">All Branches / Divisions</option>{orgs.map(([id,name])=><option key={id}value={id}>{name}</option>)}</select></label><label><span>Item Type / Asset</span><select value={asset}onChange={e=>setAsset(e.target.value)}><option value="">All Assets</option>{assets.map(x=><option key={x.id}value={x.id}>{x.name}</option>)}</select></label><label><span>Procurement Status</span><select value={status}onChange={e=>setStatus(e.target.value)}><option value="">All Statuses</option>{statusOptions.map(([code,name])=><option key={code}value={code}>{name}</option>)}</select></label><button onClick={search}><Search/>Search</button><button className="reset"onClick={reset}><RotateCcw/>Reset</button></section>
 <section className="pt-list"><div className="pt-title"><div><h2>Procurement Tracking List</h2><p>{rows.length} requisition{rows.length===1?'':'s'} found</p></div><FileSearch/></div><div className="pt-actions"><b>{selected.length} selected</b><button disabled={!selected.length}onClick={()=>setMode('status')}>Update Status</button><button disabled={!selected.length}onClick={()=>setMode('work-order')}><BriefcaseBusiness/>Work Order</button><button className="clear"disabled={!selected.length}onClick={()=>setSelected([])}>Clear Selection</button></div>{loading?<LoadingState label="Loading procurement tracking…"/>:<div className="table-scroll"><table><thead><tr><th><input type="checkbox"checked={!!rows.length&&selected.length===rows.length}onChange={e=>setSelected(e.target.checked?rows.map(x=>x.requisitionId):[])}/></th><th>Requisition No</th><th>Branch / Division</th><th>Asset</th><th>Type</th><th>Amount (BDT)</th><th>Current Status</th><th>Reference No</th><th>Last Updated</th><th>Action</th></tr></thead><tbody>{rows.map(x=><tr key={x.procurementId}><td><input type="checkbox"checked={selected.includes(x.requisitionId)}onChange={()=>toggle(x.requisitionId)}/></td><td><strong>{x.requisitionNo}</strong></td><td>{x.orgUnitName}</td><td>{x.assets}</td><td>{x.requisitionTypes.replaceAll('_',' ')}</td><td>{x.totalEstimatedAmount.toLocaleString()}</td><td><span className={`pt-status ${tone(x.statusCode)}`}>{x.statusName}</span></td><td>{x.referenceNo||'—'}</td><td>{new Date(x.modifiedDate).toLocaleString('en-GB')}</td><td><button className="pt-view"onClick={()=>void open(x.requisitionId)}title="View tracking history"><Eye/></button></td></tr>)}</tbody></table>{!rows.length&&<p className="pt-empty">No procurement tracking records match these filters.</p>}</div>}<footer>Showing {rows.length?1:0} to {rows.length} of {rows.length} entries</footer></section>
 {detail&&<div className="pt-modal-backdrop"><aside className="pt-modal"><button className="close"onClick={()=>setDetail(null)}><X/></button><h2>{detail.requisitionNo}</h2><p>{detail.orgUnitName}</p><div className="pt-current"><small>Current Status</small><b>{detail.statusName}</b><span>Reference: {detail.referenceNo||'—'}</span></div><h3>Status History</h3>{detail.history.map(x=><article key={x.id}><i/><div><b>{x.statusName}</b><span>{new Date(x.statusDate).toLocaleString('en-GB')} • {x.changedByEmployeeId}</span>{x.referenceNo&&<small>Reference: {x.referenceNo}</small>}{x.remarks&&<p>{x.remarks}</p>}</div></article>)}{!detail.history.length&&<p>No status history recorded.</p>}</aside></div>}
 {mode&&<div className="pt-dialog-backdrop"><section className="pt-dialog"><button className="close"onClick={closeAction}><X/></button><h2>{mode==='status'?'Update Procurement Status':'Work Order Information'}</h2><p className="sub">{selectedRows.length} selected requisition{selectedRows.length===1?'':'s'} · BDT {selectedRows.reduce((a,x)=>a+x.totalEstimatedAmount,0).toLocaleString()}</p><div className="selected-chips">{selectedRows.map(x=><span key={x.requisitionId}>{x.requisitionNo}<small>{x.statusName}</small></span>)}</div>{results?<ResultList results={results}/>:mode==='status'?<div className="pt-form"><label>New Status *<select value={newStatus}onChange={e=>setNewStatus(e.target.value)}><option value="">Select new status</option>{statusOptions.map(([code,name])=><option key={code}value={code}>{name}</option>)}</select></label><label>Status Date *<input type="date"max={today()}value={statusDate}onChange={e=>setStatusDate(e.target.value)}/></label><label>Reference No (Optional)<input value={referenceNo}onChange={e=>setReferenceNo(e.target.value)}/></label><label className="wide">Remarks<textarea value={statusRemarks}onChange={e=>setStatusRemarks(e.target.value)}placeholder="Enter status remarks"/></label></div>:<div className="pt-form"><label>Work Order No *<input value={workOrderNo}onChange={e=>setWorkOrderNo(e.target.value)}/></label><label>Work Order Date *<input type="date"value={workOrderDate}onChange={e=>setWorkOrderDate(e.target.value)}/></label><label>Supplier / Vendor *<input value={supplier}onChange={e=>setSupplier(e.target.value)}/></label><label>Contract / Agreement No<input value={contractNo}onChange={e=>setContractNo(e.target.value)}/></label><label>Work Order Value (BDT) *<input type="number"min="0"value={workOrderValue}onChange={e=>setWorkOrderValue(e.target.value)}/></label><label>Delivery Date<input type="date"min={workOrderDate}value={deliveryDate}onChange={e=>setDeliveryDate(e.target.value)}/></label><label className="wide">Remarks<textarea value={workRemarks}onChange={e=>setWorkRemarks(e.target.value)}/></label></div>}<div className="dialog-buttons"><button className="cancel"onClick={closeAction}>{results?'Close':'Cancel'}</button>{!results&&<button disabled={saving}onClick={()=>void(mode==='status'?submitStatus():submitWorkOrder())}>{saving?'Processing…':mode==='status'?'Save Status':'Save Work Order & Update Status'}</button>}</div></section></div>}
 {error&&<Toast tone="error"message={error}onClose={()=>setError('')}/>} {notice&&<Toast tone="success"message={notice}onClose={()=>setNotice('')}/>}</div>;
}

function ResultList({results}:{results:BatchItemResult[]}){return <div className="pt-results"><h3>Processing Result</h3>{results.map(x=><div key={x.requisitionId}className={x.resultCode==='000'?'ok':'failed'}><b>{x.requisitionNo||`Requisition ${x.requisitionId}`}</b><span>{x.resultCode==='000'?'Successful':'Failed'} — {x.resultMessage}</span></div>)}</div>}
