import { AlertCircle, CheckCircle2, Download, Layers3, XCircle } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Button } from '../../components/common/Button';
import { useAuth } from '../../auth/useAuth';
import type { AuthorityBulkResult } from '../../types/procurementAuthority';
import type { AuthorityBulkReviewItem } from './ProcurementAuthorityBulkReviewPage';

interface ResultPayload{result:AuthorityBulkResult;items:AuthorityBulkReviewItem[];remarks:string;actionAt:string}
function readPayload(state:unknown):ResultPayload|null{if(state)return state as ResultPayload;try{return JSON.parse(sessionStorage.getItem('pa-bulk-result')??'null') as ResultPayload|null}catch{return null}}

export function ProcurementAuthorityBulkResultPage(){
  const location=useLocation(),navigate=useNavigate(),data=readPayload(location.state),{user}=useAuth();
  if(!data)return <div className="pa-page"><header><h1>Bulk Approval Result</h1><p>No bulk result is available.</p></header><Button onClick={()=>navigate('/procurement-authority/requisitions')}>Back to Dashboard</Button></div>;
  const {result,items}=data,successful=result.successfulCount,failed=result.failedCount;
  const outcome=failed===0?'Successful':successful===0?'Failed':'Partial Success',tone=failed===0?'success':successful===0?'failed':'partial';
  const itemById=new Map(items.map(x=>[x.pending.id,x]));
  const concernCount=result.results.filter(x=>x.resultCode==='000'&&x.nextDestination==='CONCERN_DIVISION').length;
  const readyCount=result.results.filter(x=>x.resultCode==='000'&&x.nextDestination==='READY_FOR_PROCUREMENT').length;
  const total=items.reduce((n,x)=>n+x.pending.totalEstimatedAmount,0),successfulAmount=result.results.filter(x=>x.resultCode==='000').reduce((n,x)=>n+(itemById.get(x.requisitionId)?.pending.totalEstimatedAmount??0),0),concernAmount=result.results.filter(x=>x.resultCode==='000'&&x.nextDestination==='CONCERN_DIVISION').reduce((n,x)=>n+(itemById.get(x.requisitionId)?.pending.totalEstimatedAmount??0),0),readyAmount=result.results.filter(x=>x.resultCode==='000'&&x.nextDestination==='READY_FOR_PROCUREMENT').reduce((n,x)=>n+(itemById.get(x.requisitionId)?.pending.totalEstimatedAmount??0),0);
  return <div className="pa-page pa-bulk pa-bulk-result"><div className="pa-breadcrumb">Home › Pending My Approval › Bulk Approval Review › Bulk Approval Result</div><header className="pa-bulk-result-head"><div><h1>Procurement Authority – Bulk Approval Result</h1><p>Bulk action results returned by the workflow API.</p></div><Button className="button--secondary" onClick={()=>navigate('/procurement-authority/requisitions')}>Back to Dashboard</Button></header>
    <section className={`pa-bulk-banner ${tone}`}>{tone==='success'?<CheckCircle2/>:tone==='failed'?<XCircle/>:<AlertCircle/>}<div><h2>{outcome==='Successful'?'Bulk action completed successfully!':outcome}</h2><p>{successful} of {result.totalSelected} requests were processed successfully.</p></div><div><small>Action Date & Time</small><strong>{new Date(data.actionAt).toLocaleString('en-GB')}</strong><small>Action By</small><strong>{user?.fullName??'Procurement Authority'}</strong></div></section>
    <div className="pa-bulk-result-metrics"><section><Layers3/><small>Total Selected</small><strong>{result.totalSelected}</strong><p>Total Amount<br/><b>BDT {total.toLocaleString()}</b></p></section><section className="green"><CheckCircle2/><small>Successful</small><strong>{successful}</strong><p>Total Amount<br/><b>BDT {successfulAmount.toLocaleString()}</b></p></section><section className="teal"><CheckCircle2/><small>Approved &amp; Forwarded</small><strong>{concernCount}</strong><p>Total Amount<br/><b>BDT {concernAmount.toLocaleString()}</b></p></section><section className="green"><CheckCircle2/><small>Approved for Procurement</small><strong>{readyCount}</strong><p>Total Amount<br/><b>BDT {readyAmount.toLocaleString()}</b></p></section><section className="red"><XCircle/><small>Failed</small><strong>{failed}</strong><p>Per-item failures</p></section></div>
    <section className="pa-result-summary"><b>Summary by Action</b><div><i style={{width:`${result.totalSelected?successful/result.totalSelected*100:0}%`}}/></div><span>Successful {successful} &nbsp; • &nbsp; Failed {failed} &nbsp; • &nbsp; Total BDT {total.toLocaleString()}</span></section>
    <div className="pa-result-layout"><section className="pa-card"><h2>Processed Items</h2><div className="po-table-wrap"><table className="po-table"><thead><tr><th>Status</th><th>Req. ID</th><th>Asset / Item</th><th>Req. Type</th><th>Concern Division</th><th>Amount (BDT)</th><th>Approval Stage</th><th>Action Taken</th><th>API Result</th></tr></thead><tbody>{result.results.map(r=>{const item=itemById.get(r.requisitionId),ok=r.resultCode==='000',next=r.nextDestination??item?.context.nextStepAfterApproval;return <tr key={r.requisitionId}><td><span className={`pa-tag ${ok?'green':'red'}`}>{ok?'Success':'Failed'}</span></td><td><strong>{r.requisitionNo??item?.pending.number??r.requisitionId}</strong></td><td>{item?.detail.items.map(i=>i.assetName).join(', ')??'—'}</td><td>{item?[...new Set(item.detail.items.map(i=>i.requisitionType))].join(', '):'—'}</td><td>{item?.context.concernDivisionName??'—'}</td><td>{item?.pending.totalEstimatedAmount.toLocaleString()??'—'}</td><td>{next==='CONCERN_DIVISION'?'Before CD':'Final Approval'}</td><td>{ok?(next==='CONCERN_DIVISION'?'Approved & Forwarded':'Approved for Procurement'):'Not completed'}</td><td><b>{r.resultCode}</b><br/><small>{r.resultMessage}</small></td></tr>})}</tbody></table></div></section><aside className="pa-card pa-result-details"><h2>Action Details</h2><small>Batch Reference</small><b>{result.batchReferenceId}</b><small>Bulk Action Type</small><p>Approve using each matched workflow route</p><small>Remarks Provided</small><p>{data.remarks}</p><div>The API returned an individual result for every request.</div><Button className="button--secondary" onClick={()=>window.print()}><Download/> Download Result Report</Button></aside></div>
    <section className="pa-bulk-important"><b>Note:</b><ul><li>Approved and forwarded items will be reviewed by their Concern Division.</li><li>Final-approval items are now Ready for Procurement.</li><li>Failed items remain unchanged and can be reviewed from the pending queue.</li></ul></section></div>
}
