import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Download, FileCheck2, Network, Search, X } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import { procurementAuthorityApi } from '../../api/modules/procurementAuthorityApi';
import { Button } from '../../components/common/Button';
import { LoadingState } from '../../components/common/LoadingState';
import { Toast } from '../../components/common/Toast';
import type { AuthorityContext, AuthorityPending } from '../../types/procurementAuthority';
import type { RequisitionDetail } from '../../types/requisitions';

export interface AuthorityBulkReviewItem { pending:AuthorityPending; detail:RequisitionDetail; context:AuthorityContext }

function selectedIds(state:unknown){
  const routed=(state as {ids?:number[]}|null)?.ids;
  if(routed?.length)return routed;
  try{return JSON.parse(sessionStorage.getItem('pa-bulk-selection')??'[]') as number[]}catch{return []}
}

export function ProcurementAuthorityBulkReviewPage(){
  const location=useLocation(),navigate=useNavigate();
  const [items,setItems]=useState<AuthorityBulkReviewItem[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
  const [remarks,setRemarks]=useState(''),[message,setMessage]=useState(''),[confirming,setConfirming]=useState(false);
  const [query,setQuery]=useState(''),[stage,setStage]=useState('ALL');
  useEffect(()=>{const ids=selectedIds(location.state);(async()=>{try{if(!ids.length)throw new Error('Select at least one pending requisition from the dashboard.');const pending=await procurementAuthorityApi.pending();const byId=new Map(pending.map(x=>[x.id,x]));const valid=ids.filter(id=>byId.has(id));const loaded=await Promise.all(valid.map(async id=>({pending:byId.get(id)!,detail:await procurementAuthorityApi.detail(id),context:await procurementAuthorityApi.context(id)})));setItems(loaded);if(loaded.length!==ids.length)setMessage('Some selected requests are no longer pending and were removed from this review.')}catch(e){setMessage((e as Error).message)}finally{setLoading(false)}})()},[location.state]);
  const total=useMemo(()=>items.reduce((n,x)=>n+x.pending.totalEstimatedAmount,0),[items]);
  const beforeConcern=items.filter(x=>x.context.nextStepAfterApproval==='CONCERN_DIVISION').length;
  const ready=items.filter(x=>x.context.nextStepAfterApproval==='READY_FOR_PROCUREMENT').length;
  const rules=new Set(items.map(x=>x.context.workflowRuleId)).size;
  const shown=items.filter(x=>`${x.pending.number} ${x.detail.orgUnitName} ${x.detail.items.map(i=>i.assetName).join(' ')}`.toLowerCase().includes(query.toLowerCase())&&(stage==='ALL'||x.context.nextStepAfterApproval===stage));
  const execute=async()=>{if(remarks.trim().length<10){setMessage('Remarks must contain at least 10 characters.');return}setBusy(true);try{const result=await procurementAuthorityApi.bulkApprove(items.map(x=>x.pending.id),remarks.trim());const resultPayload={result,items,remarks:remarks.trim(),actionAt:new Date().toISOString()};sessionStorage.setItem('pa-bulk-result',JSON.stringify(resultPayload));sessionStorage.removeItem('pa-bulk-selection');navigate('/procurement-authority/requisitions/bulk-result',{replace:true,state:resultPayload})}catch(e){setMessage((e as Error).message)}finally{setBusy(false);setConfirming(false)}};
  if(loading)return <LoadingState label="Loading bulk approval review…"/>;
  return <div className="pa-page pa-bulk"><div className="pa-breadcrumb">Home › Pending My Approval › Bulk Approval Review</div><header><h1>Procurement Authority – Bulk Approval Review</h1><p>Review the selected requisitions and their database workflow destinations before confirming.</p></header>
    <div className="pa-bulk-metrics"><section><FileCheck2/><small>Selected Requisitions</small><strong>{items.length}</strong><p>Total BDT {total.toLocaleString()}</p></section><section className="amber"><Network/><small>Before Concern Division</small><strong>{beforeConcern}</strong><p>Will route to Concern Division</p></section><section className="green"><CheckCircle2/><small>Final Approval</small><strong>{ready}</strong><p>Will become Ready for Procurement</p></section><section className="purple"><Network/><small>Matched Workflow Rules</small><strong>{rules}</strong><p>Different rules</p></section></div>
    <div className="pa-bulk-layout"><section className="pa-card pa-bulk-review-table"><div className="pa-bulk-review-filters"><label>Approval Stage<select value={stage} onChange={e=>setStage(e.target.value)}><option value="ALL">All</option><option value="CONCERN_DIVISION">Before Concern Division</option><option value="READY_FOR_PROCUREMENT">Final Approval</option></select></label><label>Search<span><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Req. ID, Asset, Branch…"/></span></label></div><div className="pa-selected"><b>{items.length} items selected</b><span>You can review up to 50 requisitions at a time.</span><button><Download/> Export List</button></div><div className="po-table-wrap"><table className="po-table"><thead><tr><th><input type="checkbox" checked readOnly/></th><th>Req. ID</th><th>Asset / Item</th><th>Req. Type</th><th>Concern Division</th><th>Requested By (Branch/Dept.)</th><th>Amount (BDT)</th><th>Approval Stage</th><th>Matched Rule</th><th>Next Destination</th></tr></thead><tbody>{shown.map(x=><tr key={x.pending.id}><td><input type="checkbox" checked readOnly/></td><td><strong>{x.pending.number}</strong></td><td>{x.detail.items.map(i=>i.assetName).join(', ')}</td><td>{[...new Set(x.detail.items.map(i=>i.requisitionType))].join(', ')}</td><td>{x.context.concernDivisionName??'—'}</td><td>{x.detail.orgUnitName}</td><td>{x.pending.totalEstimatedAmount.toLocaleString()}</td><td><span className={`pa-tag ${x.context.nextStepAfterApproval==='READY_FOR_PROCUREMENT'?'green':'amber'}`}>{x.context.nextStepAfterApproval==='READY_FOR_PROCUREMENT'?'Final Approval':'Before CD'}</span></td><td><span className="pa-tag purple">{x.context.ruleCode}</span><small className="pa-rule-name">{x.context.ruleName}</small></td><td>{x.context.nextStepAfterApproval.replaceAll('_',' ')}</td></tr>)}</tbody></table>{!shown.length&&<div className="po-empty">No selected requests match these filters.</div>}</div><div className="pa-bulk-legend"><span><i className="amber"/> Before CD = Before Concern Division</span><span><i className="green"/> Final Approval = Ready for Procurement after approval</span></div></section>
      <aside className="pa-card pa-bulk-decision"><h2>Your Bulk Decision</h2><small>Approval Stage of Selected Items</small><div className="pa-stage-summary"><span><b>Before Concern Division</b><strong>{beforeConcern}</strong><small>BDT {items.filter(x=>x.context.nextStepAfterApproval==='CONCERN_DIVISION').reduce((n,x)=>n+x.pending.totalEstimatedAmount,0).toLocaleString()}</small></span><span><b>Final Approval</b><strong>{ready}</strong><small>BDT {items.filter(x=>x.context.nextStepAfterApproval==='READY_FOR_PROCUREMENT').reduce((n,x)=>n+x.pending.totalEstimatedAmount,0).toLocaleString()}</small></span></div><div className="pa-bulk-info">Each item will follow its API/database workflow destination.</div><label>Remarks <b>*</b><textarea value={remarks} onChange={e=>setRemarks(e.target.value)} maxLength={2000} placeholder="Enter your remarks here…"/></label><small>Minimum 10 characters.</small><Button disabled={!items.length||busy} onClick={()=>remarks.trim().length>=10?setConfirming(true):setMessage('Remarks must contain at least 10 characters.')}><CheckCircle2/> Confirm Bulk Action</Button><Button className="button--secondary" onClick={()=>navigate('/procurement-authority/requisitions')}>Cancel</Button></aside></div>
    <section className="pa-bulk-important"><b>Important Notes</b><ul><li>Each item will move to the next stage defined by its matched workflow rule.</li><li>The API will return a separate success or failure result for every selected request.</li><li>No frontend-only success state is assumed.</li></ul></section>
    {confirming&&<div className="pa-modal-backdrop"><div className="pa-modal" role="dialog" aria-modal="true"><button className="pa-modal-close" onClick={()=>setConfirming(false)}><X/></button><AlertTriangle/><h2>Final Confirmation</h2><p>Approve {items.length} selected requisitions using their API/database workflow destinations?</p><div><Button className="button--secondary" onClick={()=>setConfirming(false)}>Cancel</Button><Button disabled={busy} onClick={()=>void execute()}>{busy?'Processing…':'Yes, Approve Selected'}</Button></div></div></div>}
    {message&&<Toast tone="error" message={message} onClose={()=>setMessage('')}/>}</div>
}
