import{useEffect,useState}from'react';
import{ArrowLeft,Building2,CalendarDays,CheckCircle2,CircleDot,FileText,GitBranch,Send,ShoppingCart,UserRound,XCircle}from'lucide-react';
import{Link,useParams}from'react-router-dom';
import{procurementAuthorityApi}from'../../api/modules/procurementAuthorityApi';
import{procurementOfficerApi}from'../../api/modules/procurementOfficerApi';
import{Button}from'../../components/common/Button';
import{LoadingState}from'../../components/common/LoadingState';
import{Toast}from'../../components/common/Toast';
import{AttachmentPreview}from'../../components/maker/AttachmentPreview';
import{useAuth}from'../../auth/useAuth';
import type{AuthorityContext,AuthorityResult}from'../../types/procurementAuthority';
import type{WorkflowHistory}from'../../types/procurementOfficer';
import type{RequisitionDetail}from'../../types/requisitions';

type Action='approve'|'forward'|'reject';
const show=(x:string)=>(x||'—').replaceAll('_',' ');
const stageLabel=(context:AuthorityContext)=>context.canForward?'Before Concern Division':'Final Approval';

export function ProcurementAuthorityReviewPage(){
 const{id}=useParams(),rid=Number(id),{user}=useAuth();const[data,setData]=useState<RequisitionDetail|null>(null),[context,setContext]=useState<AuthorityContext|null>(null),[history,setHistory]=useState<WorkflowHistory[]>([]),[action,setAction]=useState<Action>('approve'),[remarks,setRemarks]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<AuthorityResult|null>(null);
 useEffect(()=>{Promise.all([procurementAuthorityApi.detail(rid),procurementAuthorityApi.context(rid),procurementOfficerApi.workflowHistory(rid)]).then(([d,c,h])=>{setData(d);setContext(c);setHistory(h)}).catch(e=>setError(e.message))},[rid]);
 const run=async()=>{if(action==='reject'&&remarks.trim().length<10)return setError('Remarks must contain at least 10 characters for rejection.');setBusy(true);try{const r=action==='approve'?await procurementAuthorityApi.approve(rid,remarks.trim()||null):action==='forward'?await procurementAuthorityApi.forward(rid,remarks.trim()||null):await procurementAuthorityApi.reject(rid,remarks.trim());setResult(r)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 if(!data&&!error)return <LoadingState label="Loading Authority review…"/>;
 if(!data||!context)return <div className="pa-page"><Link className="button button--secondary" to="/procurement-authority/requisitions"><ArrowLeft/> Back to Dashboard</Link>{error&&<Toast tone="error" message={error} onClose={()=>setError('')}/>}</div>;
 if(result&&action!=='reject')return <AuthoritySuccess data={data} context={context} history={history} result={result} remarks={remarks} actorName={user?.fullName??user?.employeeId??'Procurement Authority'} actorTitle={user?.designation??'Procurement Authority'}/>;
 const itemTypes=[...new Set(data.items.map(x=>show(x.requisitionType)))].join(', '),assets=data.items.map(x=>x.assetName).join(', '),quantity=data.items.reduce((n,x)=>n+x.quantity,0);
 return <div className="pa-page pa-decision-page">
  <div className="pa-breadcrumb">Home › Pending My Approval › Review &amp; Decision</div>
  <header className="pa-decision-head"><div><h1>Procurement Authority – Review &amp; Decision</h1><p>Review all details, previous processing and recommendation before taking your decision.</p></div><Link className="button button--secondary" to="/procurement-authority/requisitions"><ArrowLeft/> Back to Dashboard</Link></header>
  {result&&<section className={`pa-result ${action==='reject'?'reject':''}`}>{action==='reject'?<XCircle/>:<CheckCircle2/>}<div><h2>{action==='reject'?'Requisition Rejected':'Action Completed Successfully'}</h2><p>{result.resultMessage}</p><strong>Destination returned by workflow: {show(result.referenceNo||'END')}</strong></div></section>}
  <div className="pa-decision-layout"><main>
   <section className="pa-card pa-decision-summary"><div><small>Requisition ID</small><strong>{data.number}</strong><small>Requisition Type</small><b>{itemTypes}</b></div><div><small>Asset / Item</small><strong>{assets}</strong><small>Amount (BDT)</small><b>{data.totalEstimatedAmount.toLocaleString()}</b></div><div><small>Concern Division</small><strong>{context.concernDivisionName??'—'}</strong><small>Requested By</small><b>{data.orgUnitName}</b></div><div><small>Requested On</small><strong>{new Date(data.requestedDate).toLocaleString('en-GB')}</strong><small>Quantity</small><b>{quantity}</b></div></section>
   <section className="pa-card pa-workflow-card"><h2><i>1</i> Matched Workflow Rule</h2><div className="pa-rule-aligned"><div className="pa-rule-facts"><span><small>Rule ID</small><b>{context.ruleCode}</b></span><span><small>Rule Name</small><b>{context.ruleName}</b></span><span><small>Current Stage</small><b>{stageLabel(context)}</b></span><span><small>Concern Division</small><b>{context.concernDivisionName??'—'}</b></span></div><div className="pa-route"><h3>Workflow Route</h3><div><RouteNode label="Procurement Officer" sub="Submitted" done/><b>→</b><RouteNode label="Procurement Authority" sub="You are here" current/><b>→</b>{context.nextStepAfterApproval==='CONCERN_DIVISION'?<RouteNode label={context.concernDivisionName??'Concern Division'} sub="Review & Recommend"/>:<RouteNode label="Ready for Procurement" sub="End of workflow"/>}</div></div></div></section>
   <div className="pa-decision-lower"><section className="pa-card"><h2><i>2</i> Previous Processing / Recommendation</h2>{history.length?history.map(x=><div className="pa-history pa-history-aligned" key={x.id}><CheckCircle2/><span><strong>{show(x.actionType)}</strong><small>{show(x.fromStage||'START')} → {show(x.toStage)}</small><small>{x.actionByEmployeeId} • {new Date(x.actionDate).toLocaleString('en-GB')}</small>{x.remarks&&<p>{x.remarks}</p>}</span></div>):<p>No previous processing was recorded.</p>}</section><section className="pa-card pa-timeline"><h2>Activity Timeline</h2>{history.map(x=><div key={x.id}><CheckCircle2/><span><b>{show(x.actionType)}</b><small>{new Date(x.actionDate).toLocaleString('en-GB')}</small></span></div>)}<div><CircleDot/><span><b>Pending Your Approval</b><small>{stageLabel(context)}</small></span></div></section></div>
   <section className="pa-card"><h2><i>3</i> Requisition Details</h2>{data.items.map(x=><div className="pa-item pa-item-aligned" key={x.id}><div><small>Asset / Item</small><strong>{x.assetName}</strong></div><div><small>Type / Quantity</small><strong>{show(x.requisitionType)} • {x.quantity}</strong></div><div><small>Purpose / Justification</small><p>{x.purposeJustification}</p></div>{x.dynamicSpecifications.length>0&&<div className="pa-specs"><small>Specifications</small><p>{x.dynamicSpecifications.map(s=>`${s.name}: ${s.textValue??s.numberValue??s.dateValue??(s.boolValue===null?'—':s.boolValue?'Yes':'No')}`).join(' • ')}</p></div>}</div>)}{data.attachments.map(x=><AttachmentPreview key={x.id} attachment={x} requisitionId={data.id}/>)}</section>
  </main><aside>
   <section className="pa-card pa-stage"><h2><Building2/> Approval Stage</h2><strong>{stageLabel(context)}</strong><p>You are acting from the shared Procurement Authority approval pool.</p></section>
   {!result&&<section className="pa-card pa-decisions pa-decisions-aligned"><h2>Your Decision</h2><h3>After Your Approval</h3><Choice active={action==='approve'} icon={<CheckCircle2/>} text={`Approve → ${show(context.nextStepAfterApproval)}`} detail={`The workflow engine will route this request to ${show(context.nextStepAfterApproval)}.`} onClick={()=>setAction('approve')}/>{context.canForward&&<Choice active={action==='forward'} icon={<Send/>} text={`Forward → ${show(context.nextStepAfterApproval)}`} detail="Forward using the configured workflow route." onClick={()=>setAction('forward')}/>}<Choice active={action==='reject'} icon={<XCircle/>} text="Reject" detail="Reject the request. The requester will be notified." reject onClick={()=>setAction('reject')}/><label>Remarks {action==='reject'&&<b>*</b>}<textarea value={remarks} maxLength={2000} onChange={e=>setRemarks(e.target.value)} placeholder="Enter your remarks here…"/></label><small>{remarks.length}/2000 characters{action==='reject'?' • minimum 10':''}</small><div className="pa-decision-buttons"><Link className="button button--secondary" to="/procurement-authority/requisitions">Cancel</Link><Button disabled={busy} onClick={()=>void run()}>{busy?'Processing…':'Confirm Decision'}</Button></div></section>}
   <section className="pa-card pa-decision-note"><FileText/><div><b>Note</b><p>Once approved, the request moves to the next workflow stage returned by the API.</p></div></section>
  </aside></div>{error&&<Toast tone="error" message={error} onClose={()=>setError('')}/>}</div>;
}

function RouteNode({label,sub,done,current}:{label:string;sub:string;done?:boolean;current?:boolean}){return <span className={`pa-route-node ${done?'done':''} ${current?'current':''}`}><i><GitBranch/></i><b>{label}</b><small>{sub}</small></span>}
function Choice({active,text,detail,reject,icon,onClick}:{active:boolean;text:string;detail:string;reject?:boolean;icon:React.ReactNode;onClick:()=>void}){return <button className={`pa-choice ${active?'active':''} ${reject?'reject':''}`} onClick={onClick}><span>{icon}</span><span><b>{text}</b><small>{detail}</small></span></button>}

function AuthoritySuccess({data,context,history,result,remarks,actorName,actorTitle}:{data:RequisitionDetail;context:AuthorityContext;history:WorkflowHistory[];result:AuthorityResult;remarks:string;actorName:string;actorTitle:string}){
 const next=show(result.referenceNo||context.nextStepAfterApproval),assets=data.items.map(x=>x.assetName).join(', '),types=[...new Set(data.items.map(x=>show(x.requisitionType)))].join(', '),now=new Date();
 return <div className="pa-page pa-success-page"><div className="pa-breadcrumb">Home › Procurement Authority Dashboard › Requisition Review &amp; Decision</div><header><h1>Action Completed Successfully</h1><p>The action has been completed successfully.</p></header>
  <section className="pa-success-hero"><div className="pa-success-mark"><CheckCircle2/></div><div><h2>Approved &amp; Forwarded Successfully!</h2><p>The requisition has been approved by Procurement Authority and routed according to the matched workflow.</p><div className="pa-success-identifiers"><span><small>Requisition ID</small><b>{data.number}</b></span><span><small>Current Status / Next Destination</small><b>{next}</b></span><span><small>Matched Rule</small><b>{context.ruleCode}</b></span></div></div></section>
  <section className="pa-card pa-success-details"><h2><FileText/> Action Details</h2><div><span><small>Action Taken</small><b>Approved &amp; Forwarded</b><small>Forwarded To</small><strong>{next}</strong></span><span><small>Action Taken By</small><strong>{actorName}</strong><p>{actorTitle}</p><small>Action Date &amp; Time</small><strong>{now.toLocaleString('en-GB')}</strong></span><span><small>Requisition Type</small><strong>{types}</strong><small>Amount (BDT)</small><strong>{data.totalEstimatedAmount.toLocaleString()}</strong><small>Asset / Item</small><strong>{assets}</strong></span></div>{remarks.trim()&&<div className="pa-success-remarks"><b>Instructions / Remarks</b><p>{remarks}</p></div>}</section>
  <section className="pa-card pa-success-progress"><h2><GitBranch/> Workflow Progress</h2><div className="pa-progress-track">{history.map(x=><span className="complete" key={x.id}><i><CheckCircle2/></i><b>{show(x.toStage)}</b><small>{show(x.actionType)}</small></span>)}<span className="complete"><i><CheckCircle2/></i><b>Procurement Authority</b><small>Approved &amp; Forwarded</small></span><span className="current"><i>{next==='READY FOR PROCUREMENT'?<ShoppingCart/>:<Building2/>}</i><b>{next}</b><small>Current Stage</small></span></div><div className="pa-success-info">The request has been forwarded using the destination returned by the workflow API.</div></section>
  <div className="pa-success-actions"><Link className="button button--secondary" to="/procurement-authority/requisitions"><ArrowLeft/> Back to Dashboard</Link><Link className="button" to={`/procurement-authority/requisitions/${data.id}`}><UserRound/> View Requisition Details</Link></div>
  <div className="pa-success-time"><CalendarDays/> Completed {now.toLocaleString('en-GB')}</div></div>
}
