import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './styles.css';
import './assetStyles.css';
import './divisionStyles.css';
import './navigationFixes.css';
import './workflowStyles.css';
import './makerStyles.css';
import './attachmentStyles.css';
import './managerStyles.css';
import './managerDashboardStyles.css';
import './managerApprovalStyles.css';
import './managerOutcomeStyles.css';
import './procurementOfficerStyles.css';
import './procurementOfficerDashboardStyles.css';
import './procurementOfficerActionStyles.css';
import './procurementAuthorityStyles.css';
import './procurementAuthorityBulkStyles.css';
import './procurementAuthorityDashboardStyles.css';
import './procurementAuthorityDecisionStyles.css';
import './procurementAuthoritySuccessStyles.css';
import './concernDivisionStyles.css';
import './brandLogos.css';
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
