import { type FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ChevronDown, ChevronUp, Copy, GripVertical, ListOrdered, Pencil, Plus, Save, Search, Settings2, Trash2, X } from 'lucide-react';
import { assetApi } from '../../api/modules/assetApi';
import { Badge } from '../../components/common/Badge';
import { Button } from '../../components/common/Button';
import { ConfirmModal } from '../../components/common/ConfirmModal';
import { EmptyState } from '../../components/common/EmptyState';
import { LoadingState } from '../../components/common/LoadingState';
import { Toast } from '../../components/common/Toast';
import { Breadcrumb } from '../../layout/Breadcrumb';
import { ContentContainer } from '../../layout/ContentContainer';
import { PageHeader } from '../../layout/PageHeader';
import type { ApiError } from '../../types';
import type { Asset, AssetCategory, AssetSaveRequest, AssetSpecification, Criticality, SpecificationSaveRequest, SpecificationType } from '../../types/assets';

const emptyAsset: AssetSaveRequest = { assetCategoryId: 0, assetCode: '', assetName: '', description: '', unitOfMeasurement: 'Unit (Nos)', defaultWarranty: null, usefulLife: null, capitalizationThreshold: null, criticality: 'MEDIUM', isInventoryItem: true, isDepreciable: true, isActive: true };
const specTypes: SpecificationType[] = ['TEXT', 'NUMBER', 'DATE', 'DROPDOWN', 'MULTI_SELECT', 'YES_NO'];
const messageOf = (error: unknown) => { const api = error as ApiError; return [api.message, ...(api.errors ?? [])].filter(Boolean).join(' ') || 'The operation could not be completed.'; };
const numberOrNull = (value: string) => value === '' ? null : Number(value);

export function AssetConfigurationPage() {
  const [assets, setAssets] = useState<Asset[]>([]); const [categories, setCategories] = useState<AssetCategory[]>([]);
  const [loading, setLoading] = useState(true); const [editing, setEditing] = useState<Asset | null | undefined>(undefined);
  const [filters, setFilters] = useState({ assetName: '', assetCode: '', assetCategoryId: '', status: 'all' });
  const [toast, setToast] = useState<{ message: string; tone: 'success' | 'error' } | null>(null);
  const refreshCategories = useCallback(async () => { try { setCategories(await assetApi.categories()); } catch (error) { setToast({ tone: 'error', message: messageOf(error) }); } }, []);
  const load = useCallback(async () => { setLoading(true); try { const [assetRows, categoryRows] = await Promise.all([assetApi.search({ isActive: filters.status === 'all' ? undefined : filters.status === 'active', assetName: filters.assetName || undefined, assetCode: filters.assetCode || undefined, assetCategoryId: filters.assetCategoryId ? Number(filters.assetCategoryId) : undefined }), assetApi.categories()]); setAssets(assetRows); setCategories(categoryRows); } catch (error) { setToast({ tone: 'error', message: messageOf(error) }); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { void load(); }, [load]);
  if (editing !== undefined) return <><AssetEditor asset={editing} categories={categories} refreshCategories={refreshCategories} onBack={() => { setEditing(undefined); void load(); }} notify={setToast} />{toast && <Toast {...toast} onClose={() => setToast(null)} />}</>;
  return <ContentContainer><Breadcrumb items={['Asset Configuration', 'Asset Master']} /><PageHeader title="Asset Configuration / Asset Master" description="Create and maintain assets / items and their specific parameters." actions={<Button onClick={() => setEditing(null)}><Plus size={17} /> Add New Asset</Button>} />
    <section className="config-card filter-card"><div className="filter-grid"><label>Asset Name<input value={filters.assetName} onChange={e => setFilters(v => ({ ...v, assetName: e.target.value }))} placeholder="Search by asset name" /></label><label>Asset Code<input value={filters.assetCode} onChange={e => setFilters(v => ({ ...v, assetCode: e.target.value }))} placeholder="Search by code" /></label><label>Asset Category<select value={filters.assetCategoryId} onChange={e => setFilters(v => ({ ...v, assetCategoryId: e.target.value }))}><option value="">All categories</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Status<select value={filters.status} onChange={e => setFilters(v => ({ ...v, status: e.target.value }))}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div></section>
    <section className="config-card table-card"><div className="section-heading"><div><h2>Asset Master</h2><p>{assets.length} asset{assets.length === 1 ? '' : 's'} found</p></div><Button className="button--secondary" onClick={() => void load()}><Search size={16} /> Refresh</Button></div>{loading ? <LoadingState label="Loading assets…" /> : assets.length === 0 ? <EmptyState title="No assets found" message="Adjust your search or add a new asset." /> : <div className="table-scroll"><table className="data-table"><thead><tr><th>Asset</th><th>Code</th><th>Category</th><th>UOM</th><th>Criticality</th><th>Status</th><th>Actions</th></tr></thead><tbody>{assets.map(asset => <tr key={asset.id}><td><strong>{asset.name}</strong><small>{asset.description || 'No description'}</small></td><td>{asset.code}</td><td>{asset.categoryName}</td><td>{asset.unitOfMeasurement}</td><td><Badge tone={asset.criticality === 'CRITICAL' || asset.criticality === 'HIGH' ? 'warning' : 'info'}>{asset.criticality}</Badge></td><td><Badge tone={asset.isActive ? 'success' : 'warning'}>{asset.isActive ? 'Active' : 'Inactive'}</Badge></td><td><button className="table-action" onClick={() => setEditing(asset)} title="Edit asset"><Pencil size={16} /></button></td></tr>)}</tbody></table></div>}</section>{toast && <Toast {...toast} onClose={() => setToast(null)} />}</ContentContainer>;
}

function AssetEditor({ asset, categories, refreshCategories, onBack, notify }: { asset: Asset | null; categories: AssetCategory[]; refreshCategories: () => Promise<void>; onBack: () => void; notify: (toast: { message: string; tone: 'success' | 'error' } | null) => void }) {
  const [form, setForm] = useState<AssetSaveRequest>(() => asset ? { assetCategoryId: asset.assetCategoryId, assetCode: asset.code, assetName: asset.name, description: asset.description, unitOfMeasurement: asset.unitOfMeasurement, defaultWarranty: asset.defaultWarranty, usefulLife: asset.usefulLife, capitalizationThreshold: asset.capitalizationThreshold, criticality: asset.criticality, isInventoryItem: asset.isInventoryItem, isDepreciable: asset.isDepreciable, isActive: asset.isActive } : { ...emptyAsset });
  const [specs, setSpecs] = useState<AssetSpecification[]>([]); const [saving, setSaving] = useState(false); const [loadingSpecs, setLoadingSpecs] = useState(Boolean(asset)); const [confirming, setConfirming] = useState(false);
  const loadSpecs = useCallback(async () => { if (!asset) return; setLoadingSpecs(true); try { const result = await assetApi.specifications(asset.id); setSpecs(result.specifications.sort((a, b) => a.displayOrder - b.displayOrder)); } catch (error) { notify({ tone: 'error', message: messageOf(error) }); } finally { setLoadingSpecs(false); } }, [asset, notify]);
  useEffect(() => { void loadSpecs(); }, [loadSpecs]);
  const set = <K extends keyof AssetSaveRequest>(key: K, value: AssetSaveRequest[K]) => setForm(v => ({ ...v, [key]: value }));
  const validate = () => { if (!form.assetName.trim()) return 'Asset name is required.'; if (!form.assetCode.trim()) return 'Asset code is required.'; if (!form.assetCategoryId) return 'Asset category is required.'; if (!form.unitOfMeasurement.trim()) return 'Unit of measurement is required.'; return ''; };
  const persistDraftSpecifications = async (assetId: number) => { for (const spec of specs.filter(item => item.isActive)) { const created = await assetApi.createSpecification(assetId, { name: spec.name, type: spec.type, isMandatory: spec.isMandatory, displayOrder: spec.displayOrder, isActive: spec.isActive }); if (created.entityId && (spec.type === 'DROPDOWN' || spec.type === 'MULTI_SELECT')) { for (const [index, option] of spec.options.filter(item => item.isActive).entries()) await assetApi.createOption(created.entityId, { value: option.value, displayOrder: index + 1, isActive: true }); } } };
  const persist = async (isActive: boolean) => { const validation = validate(); if (validation) { notify({ tone: 'error', message: validation }); return; } setSaving(true); try { const payload = { ...form, isActive }; const result = asset ? await assetApi.update(asset.id, payload) : await assetApi.create(payload); if (!asset && result.entityId) { await persistDraftSpecifications(result.entityId); if (!isActive) await assetApi.setActive(result.entityId, false); } notify({ tone: 'success', message: isActive ? 'Asset saved and activated.' : 'Asset saved as inactive draft.' }); if (!asset && result.entityId) onBack(); } catch (error) { notify({ tone: 'error', message: messageOf(error) }); } finally { setSaving(false); } };
  const save = (event: FormEvent) => { event.preventDefault(); void persist(true); };
  const duplicate = async () => { if (!asset) return; setSaving(true); try { await assetApi.create({ ...form, assetCode: `${form.assetCode}-COPY`, assetName: `${form.assetName} Copy`, isActive: false }); notify({ tone: 'success', message: 'A duplicate asset draft was created.' }); onBack(); } catch (error) { notify({ tone: 'error', message: messageOf(error) }); } finally { setSaving(false); } };
  const deactivate = async () => { if (!asset) return; setConfirming(false); try { await assetApi.setActive(asset.id, !asset.isActive); notify({ tone: 'success', message: asset.isActive ? 'Asset deactivated.' : 'Asset activated.' }); onBack(); } catch (error) { notify({ tone: 'error', message: messageOf(error) }); } };
  return <ContentContainer><Breadcrumb items={['Asset Configuration', 'Asset Master', asset ? 'Edit Asset' : 'Add Asset']} /><PageHeader title="Asset Configuration / Asset Master" description="Create and maintain assets / items and their specific parameters." actions={<div className="header-actions"><Button className="button--secondary" onClick={onBack}><ArrowLeft size={16} /> Back to List</Button><Button className="button--secondary" onClick={() => asset ? void duplicate() : notify({ tone: 'error', message: 'Select an existing asset from the list before duplicating it.' })} disabled={saving}><Copy size={16} /> Duplicate Asset</Button><Button onClick={() => asset ? undefined : setForm({ ...emptyAsset })}><Plus size={16} /> Add New Asset</Button></div>} />
      <form onSubmit={save}><section className="config-card"><div className="section-heading"><h2>Asset Basic Information</h2></div><div className="asset-form-grid"><Field label="Asset Name" required><input value={form.assetName} maxLength={200} onChange={e => set('assetName', e.target.value)} /></Field><Field label="Asset Code" required hint="Unique code for the asset / item"><input value={form.assetCode} maxLength={30} onChange={e => set('assetCode', e.target.value)} /></Field><Field label="Asset Category" required><select value={form.assetCategoryId} onFocus={() => void refreshCategories()} onChange={e => set('assetCategoryId', Number(e.target.value))}><option value={0}>Select category</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Status" required><select value={form.isActive ? 'true' : 'false'} onChange={e => set('isActive', e.target.value === 'true')}><option value="true">Active</option><option value="false">Inactive</option></select></Field><Field label="Unit of Measurement" required><input value={form.unitOfMeasurement} maxLength={50} onChange={e => set('unitOfMeasurement', e.target.value)} /></Field><Field label="Default Warranty (Months)" hint="Default warranty period in months"><input type="number" min="0" value={form.defaultWarranty ?? ''} onChange={e => set('defaultWarranty', numberOrNull(e.target.value))} /></Field><Field label="Useful Life (Months)" hint="Useful life for depreciation / planning"><input type="number" min="1" value={form.usefulLife ?? ''} onChange={e => set('usefulLife', numberOrNull(e.target.value))} /></Field><Field label="Capitalization Threshold (BDT)" hint="Minimum value for capitalization"><input type="number" min="0" step="0.01" value={form.capitalizationThreshold ?? ''} onChange={e => set('capitalizationThreshold', numberOrNull(e.target.value))} /></Field><Field label="Criticality" required><select value={form.criticality} onChange={e => set('criticality', e.target.value as Criticality)}>{(['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] as Criticality[]).map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Is Inventory Item?"><RadioBoolean value={form.isInventoryItem} onChange={v => set('isInventoryItem', v)} name="inventory" /></Field><Field label="Is Depreciable?"><RadioBoolean value={form.isDepreciable} onChange={v => set('isDepreciable', v)} name="depreciable" /></Field><Field label="Description"><textarea value={form.description ?? ''} maxLength={1000} onChange={e => set('description', e.target.value)} /></Field></div></section>
      <SpecificationBuilder assetId={asset?.id} specs={specs} setSpecs={setSpecs} loading={loadingSpecs} reload={loadSpecs} notify={notify} />
      <div className="form-footer"><div><Button type="button" className="button--secondary" onClick={onBack}>Cancel</Button><Button type="button" className="button--secondary" onClick={() => setForm(asset ? { assetCategoryId: asset.assetCategoryId, assetCode: asset.code, assetName: asset.name, description: asset.description, unitOfMeasurement: asset.unitOfMeasurement, defaultWarranty: asset.defaultWarranty, usefulLife: asset.usefulLife, capitalizationThreshold: asset.capitalizationThreshold, criticality: asset.criticality, isInventoryItem: asset.isInventoryItem, isDepreciable: asset.isDepreciable, isActive: asset.isActive } : { ...emptyAsset })}>Reset</Button>{asset && <Button type="button" className="button--danger" onClick={() => setConfirming(true)}>{asset.isActive ? 'Deactivate' : 'Activate'}</Button>}</div><div><Button type="button" className="button--secondary" disabled={saving} onClick={() => void persist(false)}><Save size={15} /> Save as Draft</Button><Button type="submit" disabled={saving}><span>✓</span>{saving ? 'Saving…' : 'Save & Activate'}</Button></div></div>
    </form><ConfirmModal open={confirming} title={asset?.isActive ? 'Deactivate asset?' : 'Activate asset?'} message="This changes availability immediately for configuration and requisition use." onCancel={() => setConfirming(false)} onConfirm={() => void deactivate()} /></ContentContainer>;
}

function Field({ label, required, hint, children }: { label: string; required?: boolean; hint?: string; children: React.ReactNode }) { return <label className="form-field"><span>{label}{required && <b> *</b>}</span>{children}{hint && <small>{hint}</small>}</label>; }
function RadioBoolean({ value, onChange, name }: { value: boolean; onChange: (value: boolean) => void; name: string }) { return <div className="radio-row"><label><input type="radio" name={name} checked={value} onChange={() => onChange(true)} /> Yes</label><label><input type="radio" name={name} checked={!value} onChange={() => onChange(false)} /> No</label></div>; }

function SpecificationBuilder({ assetId, specs, setSpecs, loading, reload, notify }: { assetId?: number; specs: AssetSpecification[]; setSpecs: React.Dispatch<React.SetStateAction<AssetSpecification[]>>; loading: boolean; reload: () => Promise<void>; notify: (toast: { message: string; tone: 'success' | 'error' } | null) => void }) {
  const [draft, setDraft] = useState<AssetSpecification | null>(null); const [expanded, setExpanded] = useState<number | null>(null); const [saving, setSaving] = useState(false);
  const add = () => setDraft({ specId: 0, name: '', type: 'TEXT', isMandatory: false, displayOrder: specs.length + 1, isActive: true, options: [] });
  const saveSpec = async (spec: AssetSpecification) => { if (!spec.name.trim()) { notify({ tone: 'error', message: 'Specification name is required.' }); return; } const supportsOptions = spec.type === 'DROPDOWN' || spec.type === 'MULTI_SELECT'; if (supportsOptions && !spec.options.some(option => option.isActive)) { notify({ tone: 'error', message: 'Dropdown and multi-select specifications require at least one active option.' }); return; } if (!assetId) { setSpecs(current => spec.specId < 0 ? current.map(item => item.specId === spec.specId ? spec : item) : [...current, { ...spec, specId: -Date.now() }]); setDraft(null); notify({ tone: 'success', message: 'Specification added to this asset draft.' }); return; } setSaving(true); try { const request: SpecificationSaveRequest = { name: spec.name, type: spec.type, isMandatory: spec.isMandatory, displayOrder: spec.displayOrder, isActive: spec.isActive }; const result = spec.specId ? await assetApi.updateSpecification(spec.specId, request) : await assetApi.createSpecification(assetId, request); const targetId = spec.specId || result.entityId; if (supportsOptions && targetId) { const existing = spec.options.filter(option => option.optionId > 0); if (existing.length) await assetApi.updateOptions(targetId, existing.map((option, index) => ({ optionId: option.optionId, value: option.value, displayOrder: index + 1, isActive: option.isActive }))); for (const [index, option] of spec.options.filter(option => option.optionId === 0 && option.isActive).entries()) await assetApi.createOption(targetId, { value: option.value, displayOrder: existing.length + index + 1, isActive: true }); } notify({ tone: 'success', message: 'Specification saved.' }); setDraft(null); await reload(); } catch (error) { notify({ tone: 'error', message: messageOf(error) }); } finally { setSaving(false); } };
  const reorder = async (index: number, direction: -1 | 1) => { const other = index + direction; if (other < 0 || other >= specs.length) return; const a = specs[index]!, b = specs[other]!; if (!assetId) { const reordered = [...specs]; reordered[index] = { ...b, displayOrder: a.displayOrder }; reordered[other] = { ...a, displayOrder: b.displayOrder }; setSpecs(reordered); return; } try { await Promise.all([assetApi.updateSpecification(a.specId, { name: a.name, type: a.type, isMandatory: a.isMandatory, displayOrder: b.displayOrder, isActive: a.isActive }), assetApi.updateSpecification(b.specId, { name: b.name, type: b.type, isMandatory: b.isMandatory, displayOrder: a.displayOrder, isActive: b.isActive })]); await reload(); } catch (error) { notify({ tone: 'error', message: messageOf(error) }); } };
  const deactivate = async (spec: AssetSpecification) => { if (!assetId) { setSpecs(current => current.filter(item => item.specId !== spec.specId)); notify({ tone: 'success', message: 'Specification removed from the asset draft.' }); return; } try { await assetApi.updateSpecification(spec.specId, { name: spec.name, type: spec.type, isMandatory: spec.isMandatory, displayOrder: spec.displayOrder, isActive: !spec.isActive }); notify({ tone: 'success', message: spec.isActive ? 'Specification deactivated.' : 'Specification activated.' }); await reload(); } catch (error) { notify({ tone: 'error', message: messageOf(error) }); } };
  return <section className="config-card specification-card"><div className="section-heading"><div><h2>General Specification</h2><p>Define specifications / parameters for this asset. These will be used during requisition.</p></div><div><Button type="button" className="button--secondary" onClick={add}><Plus size={16} /> Add Specification</Button><Button type="button" className="button--secondary" disabled={specs.length < 2}><ListOrdered size={16} /> Reorder</Button></div></div>{loading ? <LoadingState label="Loading specifications…" /> : <div className="table-scroll"><table className="data-table specification-table"><thead><tr><th>SL</th><th>Specification Name</th><th>Data Type</th><th>Is Mandatory</th><th>Configuration</th><th>Actions</th></tr></thead><tbody>{specs.map((spec, index) => <SpecRow key={spec.specId} spec={spec} index={index} editing={draft?.specId === spec.specId} expanded={expanded === spec.specId} onEdit={() => setDraft({ ...spec, options: spec.options.map(x => ({ ...x })) })} onChange={setDraft} onSave={saveSpec} onCancel={() => setDraft(null)} onExpand={() => setExpanded(v => v === spec.specId ? null : spec.specId)} onDeactivate={() => void deactivate(spec)} onMove={direction => void reorder(index, direction)} saving={saving} reload={reload} notify={notify} />)}{draft?.specId === 0 && <SpecRow spec={draft} index={specs.length} editing expanded onEdit={() => undefined} onChange={setDraft} onSave={saveSpec} onCancel={() => setDraft(null)} onExpand={() => undefined} onDeactivate={() => setDraft(null)} onMove={() => undefined} saving={saving} reload={reload} notify={notify} />}</tbody></table>{specs.length === 0 && !draft && <EmptyState title="No specifications configured" message="Add the first dynamic specification for this asset." />}</div>}<div className="table-total">Total Specifications: {specs.length}</div></section>;
}

function SpecRow({ spec, index, editing, expanded, onEdit, onChange, onSave, onCancel, onExpand, onDeactivate, onMove, saving, reload, notify }: { spec: AssetSpecification; index: number; editing: boolean; expanded: boolean; onEdit: () => void; onChange: (value: AssetSpecification) => void; onSave: (value: AssetSpecification) => Promise<void>; onCancel: () => void; onExpand: () => void; onDeactivate: () => void; onMove: (direction: -1 | 1) => void; saving: boolean; reload: () => Promise<void>; notify: (toast: { message: string; tone: 'success' | 'error' } | null) => void }) {
  const supportsOptions = spec.type === 'DROPDOWN' || spec.type === 'MULTI_SELECT';
  return <><tr className={!spec.isActive ? 'row-inactive' : ''}><td><span className="row-order">{index + 1}<GripVertical size={14} /></span></td><td>{editing ? <input value={spec.name} onChange={e => onChange({ ...spec, name: e.target.value })} placeholder="Specification name" /> : <strong>{spec.name}</strong>}</td><td>{editing ? <select value={spec.type} onChange={e => onChange({ ...spec, type: e.target.value as SpecificationType, options: [] })}>{specTypes.map(type => <option key={type}>{type}</option>)}</select> : spec.type.replace('_', ' ')}</td><td><label className="switch"><input type="checkbox" checked={spec.isMandatory} disabled={!editing} onChange={e => onChange({ ...spec, isMandatory: e.target.checked })} /><span /></label></td><td>{supportsOptions ? <button type="button" className="option-trigger" onClick={onExpand}><Settings2 size={15} /> {spec.options.filter(x => x.isActive).map(x => x.value).slice(0, 2).join(', ') || 'Configure options'} {expanded ? <ChevronUp size={14} /> : <ChevronDown size={14} />}</button> : <span className="configuration-value">Value entered during requisition</span>}</td><td><div className="row-actions">{editing ? <><button type="button" className="table-action table-action--save" disabled={saving} onClick={() => void onSave(spec)}>Save</button><button type="button" className="table-action" onClick={onCancel}><X size={15} /></button></> : <><button type="button" className="table-action" onClick={onEdit}><Pencil size={15} /></button><button type="button" className="table-action" onClick={() => onMove(-1)} title="Move up"><ChevronUp size={15} /></button><button type="button" className="table-action" onClick={() => onMove(1)} title="Move down"><ChevronDown size={15} /></button><button type="button" className="table-action table-action--delete" onClick={onDeactivate}><Trash2 size={15} /></button></>}</div></td></tr>{expanded && supportsOptions && <tr className="option-row"><td /><td colSpan={5}><OptionConfiguration spec={spec} editing={editing} onChange={onChange} reload={reload} notify={notify} /></td></tr>}</>;
}

function OptionConfiguration({ spec, editing, onChange, reload, notify }: { spec: AssetSpecification; editing: boolean; onChange: (value: AssetSpecification) => void; reload: () => Promise<void>; notify: (toast: { message: string; tone: 'success' | 'error' } | null) => void }) {
  const [value, setValue] = useState(''); const activeOptions = useMemo(() => spec.options.filter(o => o.isActive), [spec.options]);
  const addLocal = () => { const clean = value.trim(); if (!clean || spec.options.some(o => o.value.toLowerCase() === clean.toLowerCase())) return; onChange({ ...spec, options: [...spec.options, { optionId: 0, value: clean, displayOrder: spec.options.length + 1, isActive: true }] }); setValue(''); };
  const addPersisted = async () => { const clean = value.trim(); if (!clean) return; try { await assetApi.createOption(spec.specId, { value: clean, displayOrder: spec.options.length + 1, isActive: true }); setValue(''); notify({ tone: 'success', message: 'Option added.' }); await reload(); } catch (error) { notify({ tone: 'error', message: messageOf(error) }); } };
  const remove = async (optionId: number) => { if (editing || optionId === 0) { onChange({ ...spec, options: spec.options.map(o => o.optionId === optionId ? { ...o, isActive: false } : o) }); return; } try { await assetApi.updateOptions(spec.specId, spec.options.map(o => ({ optionId: o.optionId, value: o.value, displayOrder: o.displayOrder, isActive: o.optionId === optionId ? false : o.isActive }))); notify({ tone: 'success', message: 'Option deactivated.' }); await reload(); } catch (error) { notify({ tone: 'error', message: messageOf(error) }); } };
  return <div className="option-config"><div><strong>{spec.type === 'DROPDOWN' ? 'Dropdown' : 'Multi-Select'} Options <b>*</b></strong><small>Enter each option and press Enter to add.</small><div className="option-tags">{activeOptions.map((option, i) => <span key={`${option.optionId}-${i}`}>{option.value}<button type="button" onClick={() => void remove(option.optionId)}><X size={12} /></button></span>)}</div><div className="option-input"><input value={value} onChange={e => setValue(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); void (editing ? addLocal() : addPersisted()); } }} placeholder="Type option and press Enter" /><button type="button" onClick={() => void (editing ? addLocal() : addPersisted())}><Plus size={16} /></button></div></div></div>;
}
