import { useCallback, useEffect, useMemo, useState } from 'react';
import { Building2, ChevronRight, Crown, Info, Plus, Search, Trash2, UserRound, UsersRound, X } from 'lucide-react';
import { divisionApi } from '../../api/modules/divisionApi';
import { Badge } from '../../components/common/Badge';
import { Button } from '../../components/common/Button';
import { ConfirmModal } from '../../components/common/ConfirmModal';
import { EmptyState } from '../../components/common/EmptyState';
import { LoadingState } from '../../components/common/LoadingState';
import { Toast } from '../../components/common/Toast';
import { Breadcrumb } from '../../layout/Breadcrumb';
import { ContentContainer } from '../../layout/ContentContainer';
import { PageHeader } from '../../layout/PageHeader';
import type { ApiError } from '../../types';
import type { ConcernAuthority, ConcernDivision, ConcernOfficial, DevelopmentEmployee } from '../../types/divisions';

type MappingKind = 'official' | 'authority';
const messageOf = (error: unknown) => { const api = error as ApiError; return [api.message, ...(api.errors ?? [])].filter(Boolean).join(' ') || 'The operation could not be completed.'; };
const today = () => new Date().toISOString().slice(0, 10);

export function DivisionOfficialSetupPage() {
  const [divisions, setDivisions] = useState<ConcernDivision[]>([]); const [selectedId, setSelectedId] = useState<number | null>(null); const [search, setSearch] = useState('');
  const [officials, setOfficials] = useState<ConcernOfficial[]>([]); const [authorities, setAuthorities] = useState<ConcernAuthority[]>([]); const [loading, setLoading] = useState(true); const [loadingMappings, setLoadingMappings] = useState(false);
  const [addKind, setAddKind] = useState<MappingKind | null>(null); const [removeTarget, setRemoveTarget] = useState<{ kind: MappingKind; id: number; name: string } | null>(null); const [toast, setToast] = useState<{ message: string; tone: 'success' | 'error' } | null>(null);
  const selected = divisions.find(x => x.id === selectedId) ?? null;
  const filtered = useMemo(() => { const term = search.trim().toLowerCase(); return term ? divisions.filter(x => `${x.orgUnitName} ${x.orgUnitCode} ${x.setupCode}`.toLowerCase().includes(term)) : divisions; }, [divisions, search]);
  const loadDivisions = useCallback(async () => { setLoading(true); try { const rows = await divisionApi.divisions(false); setDivisions(rows); setSelectedId(current => current && rows.some(x => x.id === current) ? current : rows[0]?.id ?? null); } catch (error) { setToast({ tone: 'error', message: messageOf(error) }); } finally { setLoading(false); } }, []);
  const loadMappings = useCallback(async () => { if (!selectedId) { setOfficials([]); setAuthorities([]); return; } setLoadingMappings(true); try { const [officialRows, authorityRows] = await Promise.all([divisionApi.officials(selectedId, false), divisionApi.authorities(selectedId, false)]); setOfficials(officialRows); setAuthorities(authorityRows); } catch (error) { setToast({ tone: 'error', message: messageOf(error) }); } finally { setLoadingMappings(false); } }, [selectedId]);
  useEffect(() => { void loadDivisions(); }, [loadDivisions]); useEffect(() => { void loadMappings(); }, [loadMappings]);
  const remove = async () => { if (!removeTarget) return; const target = removeTarget; setRemoveTarget(null); try { if (target.kind === 'official') await divisionApi.removeOfficial(target.id); else await divisionApi.removeAuthority(target.id); setToast({ tone: 'success', message: `${target.kind === 'official' ? 'Concern official' : 'Division authority'} deactivated.` }); await loadMappings(); } catch (error) { setToast({ tone: 'error', message: messageOf(error) }); } };
  return <ContentContainer><Breadcrumb items={['Home', 'Configuration', 'Division & Official Setup']} /><PageHeader title="Division & Official Setup" description="Configure Concern Divisions, Reviewing Officials and Division Authorities. Concern Officials decide whether a request needs Division Authority approval." />
    <div className="division-layout"><aside className="division-list config-card"><h2><ChevronRight size={16} /> Concern Divisions</h2><label className="division-search"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search division…" /><Search size={16} /></label>{loading ? <LoadingState label="Loading divisions…" /> : filtered.length === 0 ? <EmptyState title="No divisions found" message="Try a different search." /> : <div className="division-options">{filtered.map((division, index) => <button key={division.id} className={division.id === selectedId ? 'active' : ''} onClick={() => setSelectedId(division.id)}><span className="division-icon">{index % 3 === 0 ? <Building2 /> : <UsersRound />}</span><span><strong>{division.orgUnitName}</strong><small>Officials {division.id === selectedId ? officials.filter(x => x.isActive).length : '—'} | Authorities {division.id === selectedId ? authorities.filter(x => x.isActive).length : '—'}</small></span><ChevronRight size={16} /></button>)}</div>}</aside>
      <main className="division-detail">{!selected ? <section className="config-card"><EmptyState title="Select a concern division" message="Choose a division to view its officials and authorities." /></section> : <><section className="division-summary config-card"><div className="division-title"><Building2 /><div><h2>{selected.orgUnitName} <Badge tone={selected.isActive ? 'success' : 'warning'}>{selected.isActive ? 'Active' : 'Inactive'}</Badge></h2><p>Total Reviewing Officials: {officials.filter(x => x.isActive).length}<i />Total Division Authorities: {authorities.filter(x => x.isActive).length}</p></div></div><div className="division-information"><span><small>Division Code</small><strong>{selected.setupCode || selected.orgUnitCode}</strong></span><span><small>Organization Unit Code</small><strong>{selected.orgUnitCode}</strong></span><span><small>Type</small><strong>{selected.orgUnitType}</strong></span><span><small>Status</small><Badge tone={selected.isActive ? 'success' : 'warning'}>{selected.isActive ? 'Active' : 'Inactive'}</Badge></span></div></section>
        {loadingMappings ? <section className="config-card"><LoadingState label="Loading officials and authorities…" /></section> : <><MappingTable kind="official" rows={officials} onAdd={() => setAddKind('official')} onRemove={(id, name) => setRemoveTarget({ kind: 'official', id, name })} /><MappingTable kind="authority" rows={authorities} onAdd={() => setAddKind('authority')} onRemove={(id, name) => setRemoveTarget({ kind: 'authority', id, name })} /></>}
        <section className="division-notes"><Info size={17} /><div><strong>Important Notes</strong><ul><li>Concern Officials decide whether to complete verification or forward to Division Authority.</li><li>Division Authorities are a separate approval pool and may contain multiple senior officials.</li><li>Mapping changes take effect immediately for new workflow assignments.</li></ul></div></section></>}</main></div>
    {addKind && selected && <EmployeeMappingModal kind={addKind} division={selected} existingIds={new Set((addKind === 'official' ? officials : authorities).filter(x => x.isActive).map(x => x.employeeId))} onClose={() => setAddKind(null)} onSaved={async message => { setAddKind(null); setToast({ tone: 'success', message }); await loadMappings(); }} notify={setToast} />}
    <ConfirmModal open={Boolean(removeTarget)} title={`Deactivate ${removeTarget?.kind === 'official' ? 'official' : 'authority'}?`} message={`${removeTarget?.name ?? 'This employee'} will no longer be active in this division mapping.`} onCancel={() => setRemoveTarget(null)} onConfirm={() => void remove()} />{toast && <Toast {...toast} onClose={() => setToast(null)} />}</ContentContainer>;
}

function MappingTable({ kind, rows, onAdd, onRemove }: { kind: MappingKind; rows: (ConcernOfficial | ConcernAuthority)[]; onAdd: () => void; onRemove: (id: number, name: string) => void }) {
  const authority = kind === 'authority';
  return <section className="mapping-card config-card"><div className="section-heading"><div><h2>{authority ? 'Division Authorities (Senior Officials)' : 'Reviewing Officials (Concern Division Officials)'}</h2><p>{authority ? 'Senior officials who can approve requests forwarded by Concern Division Officials.' : 'Officials who review requests and decide whether to complete or forward them.'}</p></div><Button className={authority ? 'button--authority' : 'button--secondary'} onClick={onAdd}><Plus size={15} /> Add {authority ? 'Authority' : 'Official'}</Button></div>{rows.length === 0 ? <EmptyState title={`No ${authority ? 'authorities' : 'officials'} mapped`} message="Add an employee to this division." /> : <div className="table-scroll"><table className="data-table mapping-table"><thead><tr><th>SL.</th><th>Employee ID</th><th>Employee Name</th><th>Designation</th><th>Email</th>{authority && <th>Level</th>}<th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map((row, i) => <tr key={row.mappingId} className={!row.isActive ? 'row-inactive' : ''}><td>{i + 1}</td><td>{row.employeeId}</td><td><strong>{row.fullName || 'Development employee'}</strong></td><td>{row.designation || '—'}</td><td>{row.email || '—'}</td>{authority && <td>{(row as ConcernAuthority).authorityLevel}</td>}<td><Badge tone={row.isActive ? 'success' : 'warning'}>{row.isActive ? 'Active' : 'Inactive'}</Badge></td><td>{row.isActive ? <button className="table-action table-action--delete" title="Deactivate mapping" onClick={() => onRemove(row.mappingId, row.fullName || row.employeeId)}><Trash2 size={15} /></button> : <span className="muted">Deactivated</span>}</td></tr>)}</tbody></table></div>}</section>;
}

function EmployeeMappingModal({ kind, division, existingIds, onClose, onSaved, notify }: { kind: MappingKind; division: ConcernDivision; existingIds: Set<string>; onClose: () => void; onSaved: (message: string) => Promise<void>; notify: (toast: { message: string; tone: 'success' | 'error' } | null) => void }) {
  const [query, setQuery] = useState(''); const [employees, setEmployees] = useState<DevelopmentEmployee[]>([]); const [selected, setSelected] = useState<DevelopmentEmployee | null>(null); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [effectiveFrom, setEffectiveFrom] = useState(today()); const [authorityLevel, setAuthorityLevel] = useState(1);
  useEffect(() => { let active = true; const timer = window.setTimeout(async () => { setLoading(true); try { const rows = await divisionApi.employees(query); if (active) setEmployees(rows); } catch (error) { if (active) notify({ tone: 'error', message: messageOf(error) }); } finally { if (active) setLoading(false); } }, 250); return () => { active = false; window.clearTimeout(timer); }; }, [query, notify]);
  const submit = async () => { if (!selected) { notify({ tone: 'error', message: 'Select an employee.' }); return; } if (existingIds.has(selected.employeeId)) { notify({ tone: 'error', message: 'This employee already has an active mapping in the selected group.' }); return; } setSaving(true); try { if (kind === 'official') await divisionApi.addOfficial(division.id, { employeeId: selected.employeeId, effectiveFrom, effectiveTo: null }); else await divisionApi.addAuthority(division.id, { employeeId: selected.employeeId, authorityLevel, effectiveFrom, effectiveTo: null }); await onSaved(kind === 'official' ? 'Concern official added.' : 'Division authority added.'); } catch (error) { notify({ tone: 'error', message: messageOf(error) }); } finally { setSaving(false); } };
  const authority = kind === 'authority';
  return <div className="modal-backdrop"><div className={`employee-modal ${authority ? 'employee-modal--authority' : ''}`} role="dialog" aria-modal="true"><button className="modal-close" onClick={onClose} aria-label="Close"><X /></button><h2>{authority ? <Crown /> : <UsersRound />} Add {authority ? 'Division Authority' : 'Reviewing Official'}</h2><p>Search and select a development employee to add as {authority ? 'a Division Authority (Senior Official)' : 'a Reviewing Official'} for {division.orgUnitName}.</p><div className="employee-modal-grid"><div><label className="modal-field"><span>Employee <b>*</b></span><div className="employee-search"><input value={query} onChange={e => { setQuery(e.target.value); setSelected(null); }} placeholder="Search employee ID, name or email" /><Search size={17} /></div></label><div className="employee-results">{loading ? <small>Searching…</small> : employees.length === 0 ? <small>No development employees found.</small> : employees.map(employee => <button key={employee.employeeId} className={selected?.employeeId === employee.employeeId ? 'active' : ''} onClick={() => setSelected(employee)}><UserRound size={20} /><span><strong>{employee.employeeId} — {employee.fullName}</strong><small>{employee.email} · {employee.orgUnitCode}</small></span></button>)}</div><label className="modal-field"><span>Effective From</span><input type="date" value={effectiveFrom} onChange={e => setEffectiveFrom(e.target.value)} /></label>{authority && <label className="modal-field"><span>Authority Level</span><input type="number" min="1" value={authorityLevel} onChange={e => setAuthorityLevel(Math.max(1, Number(e.target.value)))} /></label>}<div className="role-notice"><Info size={16} />This user will be added as {authority ? 'a Division Authority in a separate senior-official pool.' : 'a Concern Division Reviewing Official.'}</div></div><div className="selected-employee"><h3>Selected User Information</h3>{selected ? <><div className="employee-avatar"><UserRound /></div><dl><dt>Employee Name</dt><dd>{selected.fullName}</dd><dt>Employee ID</dt><dd>{selected.employeeId}</dd><dt>Designation</dt><dd>{selected.designation}</dd><dt>Organization</dt><dd>{selected.orgUnitCode}</dd><dt>Email</dt><dd>{selected.email}</dd><dt>Account Status</dt><dd><Badge tone="success">Active</Badge></dd></dl></> : <EmptyState title="No employee selected" message="Select an employee from the search results." />}</div></div><div className="employee-modal-actions"><Button className="button--secondary" onClick={onClose}>Cancel</Button><Button className={authority ? 'button--authority' : ''} disabled={!selected || saving} onClick={() => void submit()}>{authority ? <Crown size={16} /> : <UsersRound size={16} />}{saving ? 'Adding…' : `Add ${authority ? 'Authority' : 'Official'}`}</Button></div></div></div>;
}
