import{BarChart3,Boxes,CircleCheck,CircleHelp,CircleX,Clock3,FilePlus2,FileText,GitBranch,Home,Mail,Phone,RotateCcw,Settings,SlidersHorizontal,UserCheck,Users}from'lucide-react';
import{NavLink,useLocation}from'react-router-dom';
import type{RoleCode}from'../types';
import{useAuth}from'../auth/useAuth';
type MenuItem={to:string;label:string;icon:typeof Home;roles?:RoleCode[]};
const workspace:MenuItem[]=[{to:'/dashboard',label:'Dashboard',icon:Home},{to:'/concern-division/requisitions',label:'Pending Action',icon:Clock3,roles:['CONCERN_OFFICIAL']},{to:'/concern-authority/requisitions',label:'Pending Authority Review',icon:Clock3,roles:['CONCERN_AUTHORITY']},{to:'/maker/requisitions/new',label:'New Requisition',icon:FilePlus2,roles:['MAKER','ADMIN']},{to:'/maker/requisitions',label:'My Requisitions',icon:FileText,roles:['MAKER','ADMIN']},{to:'/manager/requisitions',label:'Pending Verification',icon:Clock3,roles:['MANAGER','ADMIN']},{to:'/procurement-officer/requisitions/pending',label:'Pending My Review',icon:CircleCheck,roles:['PROCUREMENT_OFFICER','ADMIN']},{to:'/procurement-officer/requisitions/mine',label:'Taken by Me',icon:UserCheck,roles:['PROCUREMENT_OFFICER']},{to:'/procurement-authority/requisitions',label:'Pending My Approval',icon:Clock3,roles:['PROCUREMENT_AUTHORITY']},{to:'/maker/requisitions?status=returned',label:'Returned for Clarification',icon:RotateCcw,roles:['MAKER','ADMIN']},{to:'/maker/requisitions?status=rejected',label:'Rejected',icon:CircleX,roles:['MAKER','ADMIN']}];
const oversight:MenuItem[]=[{to:'/procurement-officer/requisitions/all',label:'All Requisitions',icon:FileText,roles:['PROCUREMENT_OFFICER','ADMIN']},{to:'/procurement/tracking',label:'Procurement Tracking',icon:FileText,roles:['PROCUREMENT_TRACKER','PROCUREMENT_AUTHORITY']},{to:'/reports',label:'Reports',icon:BarChart3,roles:['ADMIN','CONCERN_OFFICIAL']}];
const configuration:MenuItem[]=[{to:'/admin/assets',label:'Asset Configuration',icon:Boxes,roles:['ADMIN']},{to:'/admin/divisions',label:'Division & Official Setup',icon:SlidersHorizontal,roles:['ADMIN']},{to:'/admin/workflow',label:'Workflow & Approval Matrix',icon:GitBranch,roles:['ADMIN']},{to:'/admin/users',label:'User & Role Management',icon:Users,roles:['ADMIN']},{to:'/admin/settings',label:'System Settings',icon:Settings,roles:['ADMIN']}];
export function Sidebar(){const{isInRole}=useAuth();const location=useLocation();const render=(items:MenuItem[])=>items.filter(x=>!x.roles||isInRole(...x.roles)).map(({to,label,icon:Icon})=>{const[urlPath,query='']=to.split('?');const exactQuery=query?location.search===`?${query}`:!location.search;const active=location.pathname===urlPath&&exactQuery;return <NavLink key={to}to={to}className={active?'nav-link active':'nav-link'}><Icon size={17}/><span>{label}</span></NavLink>});return <aside className="sidebar"><div className="brand"><picture className="brand-logo"><source media="(max-width: 900px)" srcSet="/brand/purple-short.png"/><img src="/brand/purple-long.png" alt="Jamuna Bank PLC"/></picture></div><nav>{render(workspace)}<div className="nav-divider"/>{render(oversight)}{isInRole('ADMIN')&&<><div className="nav-divider"/><p className="nav-caption">Configuration</p>{render(configuration)}</>}</nav><div className="help-card"><CircleHelp size={23}/><div><strong>Need Help?</strong><small>Contact ICT Help Desk</small></div><p><Phone size={14}/> 16276</p><p><Mail size={14}/> ict.helpdesk@jamunabank.com.bd</p></div><footer className="sidebar-footer"><img className="footer-logo" src="/brand/jamuna-bank-white.png" alt="Jamuna Bank PLC"/><small>© 2026 All rights reserved.</small></footer></aside>}
